/**
 * AppFolio-derived fixture — communications
 *
 * GENERATED by Scripts/derive_appfolio_fixtures.mjs — DO NOT EDIT BY HAND.
 * Source: AppFolio_Screenshots/data/*.json (captured 2026-04-19).
 *
 * Gated by VITE_APPFOLIO_SEEDS per GR-7. When flag is false this module
 * exports empty arrays so no real-person data leaks into public builds.
 */
/* eslint-disable */

const ENABLED = (import.meta as any).env?.VITE_APPFOLIO_SEEDS !== 'false';

export interface AppfolioCommunication {
    id: string;
    channel: 'email' | 'sms' | 'portal' | string;
    direction: 'inbound' | 'outbound';
    sentAt: string | null;
    fromAddress: string | null;
    toAddress: string | null;
    subject: string | null;
    readStatus: string | null;
    entityId: string | null;
    source: string;
}
export const APPFOLIO_COMMUNICATIONS: AppfolioCommunication[] = ENABLED ? [
    {
        "id": "appfolio-comm-1",
        "channel": "email",
        "direction": "outbound",
        "sentAt": "2026-04-16 04:55 PM",
        "fromAddress": "ashley.johnson@zp-group.example",
        "toAddress": "tenant-0@example.com",
        "subject": "Important Community Notice: Vehicle Safety Reminder",
        "readStatus": "Opened",
        "entityId": "appfolio-occ-2800",
        "source": "appfolio-tenant-emails-willie-white"
    },
    {
        "id": "appfolio-comm-2",
        "channel": "email",
        "direction": "outbound",
        "sentAt": "2026-04-15 03:44 PM",
        "fromAddress": "ashley.johnson@zp-group.example",
        "toAddress": "tenant-1@example.com",
        "subject": "Paperless Payment Transition & Resident Portal Instructions",
        "readStatus": "Opened",
        "entityId": "appfolio-occ-2800",
        "source": "appfolio-tenant-emails-willie-white"
    },
    {
        "id": "appfolio-comm-3",
        "channel": "email",
        "direction": "outbound",
        "sentAt": "2026-04-15 03:42 PM",
        "fromAddress": "ashley.johnson@zp-group.example",
        "toAddress": "tenant-2@example.com",
        "subject": "Important Update: Changes to Accepted Payment Methods Effective April 30, 2026",
        "readStatus": "Opened",
        "entityId": "appfolio-occ-2800",
        "source": "appfolio-tenant-emails-willie-white"
    },
    {
        "id": "appfolio-comm-4",
        "channel": "email",
        "direction": "outbound",
        "sentAt": "2026-04-14 01:47 PM",
        "fromAddress": "ashley.johnson@zp-group.example",
        "toAddress": "tenant-3@example.com",
        "subject": "Water Service Interruption Notice - April 15, 2026",
        "readStatus": "Opened",
        "entityId": "appfolio-occ-2800",
        "source": "appfolio-tenant-emails-willie-white"
    },
    {
        "id": "appfolio-comm-5",
        "channel": "email",
        "direction": "outbound",
        "sentAt": "2026-04-13 03:36 PM",
        "fromAddress": "ashley.johnson@zp-group.example",
        "toAddress": "tenant-4@example.com",
        "subject": "Community Garden Launch",
        "readStatus": "Opened",
        "entityId": "appfolio-occ-2800",
        "source": "appfolio-tenant-emails-willie-white"
    },
    {
        "id": "appfolio-comm-6",
        "channel": "email",
        "direction": "outbound",
        "sentAt": "2026-04-09 01:26 PM",
        "fromAddress": "ashley.johnson@zp-group.example",
        "toAddress": "tenant-5@example.com",
        "subject": "Online Rent Payments & Community Reminder",
        "readStatus": "Opened",
        "entityId": "appfolio-occ-2800",
        "source": "appfolio-tenant-emails-willie-white"
    },
    {
        "id": "appfolio-comm-7",
        "channel": "email",
        "direction": "outbound",
        "sentAt": "2026-03-27 05:04 PM",
        "fromAddress": "ashley.johnson@zp-group.example",
        "toAddress": "tenant-6@example.com",
        "subject": "Sidewalk Notice - Wet Concrete",
        "readStatus": "Opened",
        "entityId": "appfolio-occ-2800",
        "source": "appfolio-tenant-emails-willie-white"
    }
] : [];
