/**
 * AppFolio-derived fixture — compliance
 *
 * GENERATED by Scripts/derive_appfolio_fixtures.mjs — DO NOT EDIT BY HAND.
 * Source: AppFolio_Screenshots/data/*.json (captured 2026-04-19).
 *
 * Gated by VITE_APPFOLIO_SEEDS per GR-7. When flag is false this module
 * exports empty arrays so no real-person data leaks into public builds.
 */
/* eslint-disable */

const ENABLED = (import.meta as any).env?.VITE_APPFOLIO_SEEDS !== 'false';

export interface AppfolioComplianceItem {
    id: string; entityType: 'vendor' | 'inspection' | 'policy' | string;
    entityId: string; entityName: string;
    kind: string; expiration: string | null;
    status: string; source: string;
}
export const APPFOLIO_COMPLIANCE_ITEMS: AppfolioComplianceItem[] = ENABLED ? [
    {
        "id": "appfolio-comp-v2716-0",
        "entityType": "vendor",
        "entityId": "appfolio-v-2716",
        "entityName": "2-STORY TECHNICAL ROOFING LLC",
        "kind": "Workers' Comp",
        "expiration": null,
        "status": "missing",
        "source": "vendor-2716"
    },
    {
        "id": "appfolio-comp-v2716-1",
        "entityType": "vendor",
        "entityId": "appfolio-v-2716",
        "entityName": "2-STORY TECHNICAL ROOFING LLC",
        "kind": "General Liability",
        "expiration": "2026-07-11",
        "status": "tracked",
        "source": "vendor-2716"
    },
    {
        "id": "appfolio-comp-v2716-2",
        "entityType": "vendor",
        "entityId": "appfolio-v-2716",
        "entityName": "2-STORY TECHNICAL ROOFING LLC",
        "kind": "EPA Certification",
        "expiration": null,
        "status": "missing",
        "source": "vendor-2716"
    },
    {
        "id": "appfolio-comp-v2716-3",
        "entityType": "vendor",
        "entityId": "appfolio-v-2716",
        "entityName": "2-STORY TECHNICAL ROOFING LLC",
        "kind": "Auto Insurance",
        "expiration": null,
        "status": "missing",
        "source": "vendor-2716"
    },
    {
        "id": "appfolio-comp-v2716-4",
        "entityType": "vendor",
        "entityId": "appfolio-v-2716",
        "entityName": "2-STORY TECHNICAL ROOFING LLC",
        "kind": "State License",
        "expiration": null,
        "status": "missing",
        "source": "vendor-2716"
    },
    {
        "id": "appfolio-comp-v2716-5",
        "entityType": "vendor",
        "entityId": "appfolio-v-2716",
        "entityName": "2-STORY TECHNICAL ROOFING LLC",
        "kind": "Contract",
        "expiration": null,
        "status": "missing",
        "source": "vendor-2716"
    },
    {
        "id": "appfolio-comp-aha-1",
        "entityType": "inspection",
        "entityId": "riverwood-club",
        "entityName": "Riverwood Club Apartments",
        "kind": "Section 8 (AHA) Inspection",
        "expiration": "2026-04-27",
        "status": "scheduled",
        "source": "appfolio-aha-inspection-batch"
    },
    {
        "id": "appfolio-comp-aha-2",
        "entityType": "inspection",
        "entityId": "riverwood-club",
        "entityName": "Riverwood Club Apartments",
        "kind": "Section 8 (AHA) Inspection",
        "expiration": "2026-04-28",
        "status": "scheduled",
        "source": "appfolio-aha-inspection-batch"
    },
    {
        "id": "appfolio-comp-aha-3",
        "entityType": "inspection",
        "entityId": "riverwood-club",
        "entityName": "Riverwood Club Apartments",
        "kind": "Section 8 (AHA) Inspection",
        "expiration": "2026-04-29",
        "status": "scheduled",
        "source": "appfolio-aha-inspection-batch"
    },
    {
        "id": "appfolio-comp-aha-4",
        "entityType": "inspection",
        "entityId": "riverwood-club",
        "entityName": "Riverwood Club Apartments",
        "kind": "Section 8 (AHA) Inspection",
        "expiration": "2026-04-30",
        "status": "scheduled",
        "source": "appfolio-aha-inspection-batch"
    },
    {
        "id": "appfolio-comp-aha-5",
        "entityType": "inspection",
        "entityId": "riverwood-club",
        "entityName": "Riverwood Club Apartments",
        "kind": "Section 8 (AHA) Inspection",
        "expiration": "2026-04-27",
        "status": "scheduled",
        "source": "appfolio-aha-inspection-batch"
    },
    {
        "id": "appfolio-comp-aha-6",
        "entityType": "inspection",
        "entityId": "riverwood-club",
        "entityName": "Riverwood Club Apartments",
        "kind": "Section 8 (AHA) Inspection",
        "expiration": "2026-04-28",
        "status": "scheduled",
        "source": "appfolio-aha-inspection-batch"
    },
    {
        "id": "appfolio-comp-aha-7",
        "entityType": "inspection",
        "entityId": "riverwood-club",
        "entityName": "Riverwood Club Apartments",
        "kind": "Section 8 (AHA) Inspection",
        "expiration": "2026-04-29",
        "status": "scheduled",
        "source": "appfolio-aha-inspection-batch"
    },
    {
        "id": "appfolio-comp-aha-8",
        "entityType": "inspection",
        "entityId": "riverwood-club",
        "entityName": "Riverwood Club Apartments",
        "kind": "Section 8 (AHA) Inspection",
        "expiration": "2026-04-30",
        "status": "scheduled",
        "source": "appfolio-aha-inspection-batch"
    },
    {
        "id": "appfolio-comp-aha-9",
        "entityType": "inspection",
        "entityId": "riverwood-club",
        "entityName": "Riverwood Club Apartments",
        "kind": "Section 8 (AHA) Inspection",
        "expiration": "2026-04-27",
        "status": "scheduled",
        "source": "appfolio-aha-inspection-batch"
    }
] : [];
export const APPFOLIO_INSURANCE_ENFORCEMENT_COLUMNS = [
    {
        "name": "Property",
        "type": "string",
        "link": "property_link"
    },
    {
        "name": "Unit",
        "type": "string",
        "link": "unit_link"
    },
    {
        "name": "Resident",
        "type": "string",
        "link": "occupancy_link"
    },
    {
        "name": "LeaseRequiresInsurance",
        "type": "string"
    },
    {
        "name": "InsuranceRequirement",
        "type": "string"
    },
    {
        "name": "ActiveCoverage",
        "type": "string"
    }
];
