/**
 * AppFolio-derived fixture — index barrel
 *
 * GENERATED by Scripts/derive_appfolio_fixtures.mjs — DO NOT EDIT BY HAND.
 * Source: AppFolio_Screenshots/data/*.json (captured 2026-04-19).
 *
 * Gated by VITE_APPFOLIO_SEEDS per GR-7. When flag is false this module
 * exports empty arrays so no real-person data leaks into public builds.
 */
/* eslint-disable */

export * from './properties';
export * from './occupancies';
export * from './tenants';
export * from './vendors';
export * from './workorders';
export * from './leases';
export * from './compliance';
export * from './communications';
export * from './fixed_assets';
