/**
 * AppFolio-derived fixture — occupancies
 *
 * GENERATED by Scripts/derive_appfolio_fixtures.mjs — DO NOT EDIT BY HAND.
 * Source: AppFolio_Screenshots/data/*.json (captured 2026-04-19).
 *
 * Gated by VITE_APPFOLIO_SEEDS per GR-7. When flag is false this module
 * exports empty arrays so no real-person data leaks into public builds.
 */
/* eslint-disable */

const ENABLED = (import.meta as any).env?.VITE_APPFOLIO_SEEDS !== 'false';

export interface AppfolioOccupancy {
    id: string; propertyName: string | null; unitLabel: string | null;
    leaseEndDate: string | null; monthlyCharges: number | null;
    currentBalance: number | null; deposit: number | null;
    primaryTenantName: string | null; otherOccupantNames: string[];
    onlinePortalStatus: string | null; source: string;
}
export const APPFOLIO_OCCUPANCIES: AppfolioOccupancy[] = ENABLED ? [
    {
        "id": "appfolio-occ-2800",
        "propertyName": "Riverwood Club Apartments - B03",
        "unitLabel": "Riverwood Club Apartments - B03",
        "leaseEndDate": "2026-09-30",
        "monthlyCharges": 1595,
        "currentBalance": -7986.4,
        "deposit": 850,
        "primaryTenantName": "LaSonta M. Westbrook",
        "otherOccupantNames": [
            "Willie White",
            "Olivia White",
            "Elijah Westbrook"
        ],
        "onlinePortalStatus": "Active",
        "source": "occupancy-2800"
    }
] : [];
