/**
 * AppFolio-derived fixture — properties
 *
 * GENERATED by Scripts/derive_appfolio_fixtures.mjs — DO NOT EDIT BY HAND.
 * Source: AppFolio_Screenshots/data/*.json (captured 2026-04-19).
 *
 * Gated by VITE_APPFOLIO_SEEDS per GR-7. When flag is false this module
 * exports empty arrays so no real-person data leaks into public builds.
 */
/* eslint-disable */

const ENABLED = (import.meta as any).env?.VITE_APPFOLIO_SEEDS !== 'false';

export interface AppfolioProperty {
    id: string; name: string;
    address: string | null; city: string | null; state: string | null; zip: string | null;
    county: string | null; yearBuilt: number | null; marketValue: number | null;
    acquisitionDate: string | null; status: 'active' | 'inactive'; source: string;
}
export const APPFOLIO_PROPERTIES: AppfolioProperty[] = ENABLED ? [
    {
        "id": "appfolio-18",
        "name": "128 BUENA VISTA DR N",
        "address": "128 Buena Vista Dr N, Dunedin, FL 34698",
        "city": null,
        "state": null,
        "zip": null,
        "county": "Pinellas County",
        "yearBuilt": null,
        "marketValue": null,
        "acquisitionDate": null,
        "status": "active",
        "source": "appfolio-property-detail-18"
    },
    {
        "id": "appfolio-p1-1",
        "name": "128 BUENA VISTA DR N",
        "address": "128 Buena Vista Dr N, Dunedin, FL 34698",
        "city": null,
        "state": null,
        "zip": null,
        "county": null,
        "yearBuilt": null,
        "marketValue": null,
        "acquisitionDate": null,
        "status": "active",
        "source": "appfolio-properties-page1"
    },
    {
        "id": "appfolio-p1-2",
        "name": "2070 AZALEA DRIVE",
        "address": "2070 Azalea Drive, Roswell, GA 30075",
        "city": null,
        "state": null,
        "zip": null,
        "county": null,
        "yearBuilt": null,
        "marketValue": null,
        "acquisitionDate": null,
        "status": "active",
        "source": "appfolio-properties-page1"
    },
    {
        "id": "appfolio-p1-3",
        "name": "2227 WAYSIDE DR",
        "address": "2227 Wayside Dr, Atlanta, GA 30319",
        "city": null,
        "state": null,
        "zip": null,
        "county": null,
        "yearBuilt": null,
        "marketValue": null,
        "acquisitionDate": null,
        "status": "active",
        "source": "appfolio-properties-page1"
    },
    {
        "id": "appfolio-p1-4",
        "name": "2262 HARBOR VIEW DRIVE",
        "address": "2262 Harbor View Dr, Dunedin, FL 34698",
        "city": null,
        "state": null,
        "zip": null,
        "county": null,
        "yearBuilt": null,
        "marketValue": null,
        "acquisitionDate": null,
        "status": "active",
        "source": "appfolio-properties-page1"
    },
    {
        "id": "appfolio-p1-5",
        "name": "305 Hilltop Drive",
        "address": "305 Hilltop Dr, Upper Sandusky, OH 43351",
        "city": null,
        "state": null,
        "zip": null,
        "county": null,
        "yearBuilt": null,
        "marketValue": null,
        "acquisitionDate": null,
        "status": "active",
        "source": "appfolio-properties-page1"
    },
    {
        "id": "appfolio-p1-6",
        "name": "4409 ST ANDREWS DR",
        "address": "4409 ST ANDREWS DR NW, ATLANTA, GA 30327",
        "city": null,
        "state": null,
        "zip": null,
        "county": null,
        "yearBuilt": null,
        "marketValue": null,
        "acquisitionDate": null,
        "status": "active",
        "source": "appfolio-properties-page1"
    },
    {
        "id": "appfolio-p1-7",
        "name": "498 Meadow Rd aka Ski Country Chalet",
        "address": "498 Meadow Rd, Snowmass Village, CO 81612",
        "city": null,
        "state": null,
        "zip": null,
        "county": null,
        "yearBuilt": null,
        "marketValue": null,
        "acquisitionDate": null,
        "status": "active",
        "source": "appfolio-properties-page1"
    },
    {
        "id": "appfolio-p1-8",
        "name": "Andre' J Zohoury",
        "address": "128 Buena Vista Dr N, Dunedin, FL 34698",
        "city": null,
        "state": null,
        "zip": null,
        "county": null,
        "yearBuilt": null,
        "marketValue": null,
        "acquisitionDate": null,
        "status": "active",
        "source": "appfolio-properties-page1"
    },
    {
        "id": "appfolio-p1-9",
        "name": "ANZO Consulting, LLC",
        "address": "128 Buena Vista Dr N, Dunedin, FL 34698",
        "city": null,
        "state": null,
        "zip": null,
        "county": null,
        "yearBuilt": null,
        "marketValue": null,
        "acquisitionDate": null,
        "status": "active",
        "source": "appfolio-properties-page1"
    },
    {
        "id": "appfolio-p1-10",
        "name": "ANZO, LLC",
        "address": "4409 SAINT ANDREWS DR NW, ATLANTA, GA 30327",
        "city": null,
        "state": null,
        "zip": null,
        "county": null,
        "yearBuilt": null,
        "marketValue": null,
        "acquisitionDate": null,
        "status": "active",
        "source": "appfolio-properties-page1"
    }
] : [];
export const APPFOLIO_PROPERTY_TOTAL = 50;
