/**
 * AppFolio-derived fixture — tenants
 *
 * GENERATED by Scripts/derive_appfolio_fixtures.mjs — DO NOT EDIT BY HAND.
 * Source: AppFolio_Screenshots/data/*.json (captured 2026-04-19).
 *
 * Gated by VITE_APPFOLIO_SEEDS per GR-7. When flag is false this module
 * exports empty arrays so no real-person data leaks into public builds.
 */
/* eslint-disable */

const ENABLED = (import.meta as any).env?.VITE_APPFOLIO_SEEDS !== 'false';

export interface AppfolioTenant {
    id: string; name: string;
    property: string | null; unit: string | null;
    status: 'Current' | 'Past' | 'Future' | string;
    phone: string | null; email: string | null;
    occupantType?: 'Primary' | 'Other Occupant';
    occupancyId?: string;
    source: string;
}
export const APPFOLIO_TENANTS: AppfolioTenant[] = ENABLED ? [
    {
        "id": "appfolio-t-1",
        "name": "De dios, Marcelina",
        "property": "Huntington Lane Apartments - 152 Dodd St, Apt D",
        "unit": "0909 A",
        "status": "Past",
        "phone": null,
        "email": null,
        "source": "appfolio-occupancies-page1"
    },
    {
        "id": "appfolio-t-2",
        "name": "Glover, Jasmine",
        "property": "Washington Gardens Apartments - 4555 Washington Rd",
        "unit": "001O",
        "status": "Past",
        "phone": null,
        "email": null,
        "source": "appfolio-occupancies-page1"
    },
    {
        "id": "appfolio-t-3",
        "name": "Harmon, Amiyah",
        "property": "Summerfield Apartments - 4581 S Kirkman Rd",
        "unit": "3901",
        "status": "Past",
        "phone": null,
        "email": null,
        "source": "appfolio-occupancies-page1"
    },
    {
        "id": "appfolio-t-4",
        "name": "NARVAEZ, ANTHONY",
        "property": "Summerfield Apartments - 4581 S Kirkman Rd",
        "unit": "9102",
        "status": "Past",
        "phone": "(555) 555-XXXX",
        "email": null,
        "source": "appfolio-occupancies-page1"
    },
    {
        "id": "appfolio-t-5",
        "name": "Palmer Jr., Kenneth",
        "property": "Riverwood Club Apartments - 901 Bolton Rd",
        "unit": "A05",
        "status": "Past",
        "phone": null,
        "email": null,
        "source": "appfolio-occupancies-page1"
    },
    {
        "id": "appfolio-t-6",
        "name": "POLEON, ISHBEL",
        "property": "Summerfield Apartments - 4581 S Kirkman Rd",
        "unit": "5501",
        "status": "Past",
        "phone": "(555) 555-XXXX",
        "email": null,
        "source": "appfolio-occupancies-page1"
    },
    {
        "id": "appfolio-t-7",
        "name": "White, Willie",
        "property": "Riverwood Club Apartments - 901 Bolton Rd",
        "unit": "B03",
        "status": "Current",
        "phone": null,
        "email": null,
        "source": "appfolio-occupancies-page1"
    },
    {
        "id": "appfolio-t-8",
        "name": "1 brm, MODEL",
        "property": "Washington Gardens Apartments",
        "unit": "001I",
        "status": "Past",
        "phone": null,
        "email": null,
        "source": "appfolio-occupancies-page1"
    },
    {
        "id": "appfolio-t-9",
        "name": "2BRM, model",
        "property": "Washington Gardens Apartments",
        "unit": "022I",
        "status": "Past",
        "phone": null,
        "email": null,
        "source": "appfolio-occupancies-page1"
    },
    {
        "id": "appfolio-t-10",
        "name": "ABDELOUAHED, HAMID",
        "property": "Summerfield Apartments",
        "unit": "2908",
        "status": "Past",
        "phone": "(555) 555-XXXX",
        "email": null,
        "source": "appfolio-occupancies-page1"
    },
    {
        "id": "appfolio-t-11",
        "name": "ABDELSADEK, MOHAMED A.",
        "property": "Summerfield Apartments",
        "unit": "6907",
        "status": "Past",
        "phone": null,
        "email": null,
        "source": "appfolio-occupancies-page1"
    },
    {
        "id": "appfolio-t-12",
        "name": "Abdulkarim, Nafisah G.",
        "property": "Woodland Parc Townhomes",
        "unit": "2779-2",
        "status": "Past",
        "phone": "(555) 555-XXXX",
        "email": null,
        "source": "appfolio-occupancies-page1"
    },
    {
        "id": "appfolio-t-13",
        "name": "ABREU, MARIO G.",
        "property": "Summerfield Apartments",
        "unit": "3905",
        "status": "Past",
        "phone": "(555) 555-XXXX",
        "email": null,
        "source": "appfolio-occupancies-page1"
    },
    {
        "id": "appfolio-t-occ2800-0",
        "name": "LaSonta M. Westbrook",
        "property": "Riverwood Club Apartments",
        "unit": "B03",
        "status": "Current",
        "phone": null,
        "email": null,
        "source": "occupancy-2800",
        "occupantType": "Primary",
        "occupancyId": "appfolio-occ-2800"
    },
    {
        "id": "appfolio-t-occ2800-1",
        "name": "Willie White",
        "property": "Riverwood Club Apartments",
        "unit": "B03",
        "status": "Current",
        "phone": null,
        "email": null,
        "source": "occupancy-2800",
        "occupantType": "Other Occupant",
        "occupancyId": "appfolio-occ-2800"
    },
    {
        "id": "appfolio-t-occ2800-2",
        "name": "Olivia White",
        "property": "Riverwood Club Apartments",
        "unit": "B03",
        "status": "Current",
        "phone": null,
        "email": null,
        "source": "occupancy-2800",
        "occupantType": "Other Occupant",
        "occupancyId": "appfolio-occ-2800"
    },
    {
        "id": "appfolio-t-occ2800-3",
        "name": "Elijah Westbrook",
        "property": "Riverwood Club Apartments",
        "unit": "B03",
        "status": "Current",
        "phone": null,
        "email": null,
        "source": "occupancy-2800",
        "occupantType": "Other Occupant",
        "occupancyId": "appfolio-occ-2800"
    }
] : [];
export const APPFOLIO_TENANT_TOTAL = 3274;
