/**
 * AppFolio-derived fixture — vendors
 *
 * GENERATED by Scripts/derive_appfolio_fixtures.mjs — DO NOT EDIT BY HAND.
 * Source: AppFolio_Screenshots/data/*.json (captured 2026-04-19).
 *
 * Gated by VITE_APPFOLIO_SEEDS per GR-7. When flag is false this module
 * exports empty arrays so no real-person data leaks into public builds.
 */
/* eslint-disable */

const ENABLED = (import.meta as any).env?.VITE_APPFOLIO_SEEDS !== 'false';

export interface AppfolioVendorCompliance {
    workers_comp_expiration: string | null;
    general_liability_expiration: string | null;
    epa_certification_expiration: string | null;
    auto_insurance_expiration: string | null;
    state_license_expiration: string | null;
    contract_expiration: string | null;
    request_compliance_documents_cta?: boolean;
}
export interface AppfolioVendorFederalTax {
    taxpayer_name?: string;
    w9_requested?: boolean;
    tax_id_masked?: string;
    tax_form_account_number?: string;
    send_1099?: boolean;
}
export interface AppfolioVendor {
    id: string; name: string;
    primaryContactName: string | null;
    website: string | null;
    vendorType: string | null;
    phoneType: string | null;
    phone: string | null;
    phoneNotes: string | null;
    emails: string[];
    primaryAddress: { type?: string; street?: string; city?: string; state?: string; zip?: string } | null;
    vendorPortalActivated: boolean;
    federalTax: AppfolioVendorFederalTax | null;
    accounting: Record<string, any> | null;
    compliance: AppfolioVendorCompliance | null;
    paymentMethod: string | null;
    send1099: boolean;
    notes: { posted_by: string; ts: string; body: string }[];
    source: string;
}
export const APPFOLIO_VENDORS: AppfolioVendor[] = ENABLED ? [
    {
        "id": "appfolio-v-2716",
        "name": "2-STORY TECHNICAL ROOFING LLC",
        "primaryContactName": "Danny Bourdua",
        "website": "www.2stroofing.com",
        "vendorType": "General",
        "phoneType": "Mobile",
        "phone": "(555) 555-XXXX",
        "phoneNotes": "Zelle linked",
        "emails": [
            "daniel@2stroofing.com",
            "tenant-v2716-1@example.com"
        ],
        "primaryAddress": {
            "type": "Primary",
            "street": "3122 OLD CORNELIA HWY",
            "city": "GAINESVILLE",
            "state": "GA",
            "zip": "30507"
        },
        "vendorPortalActivated": true,
        "federalTax": {
            "taxpayer_name": "2-STORY TECHNICAL ROOFING",
            "w9_requested": true,
            "tax_id_masked": "XX-XX-XXXX",
            "tax_form_account_number": "T5880725740908400331",
            "send_1099": true
        },
        "accounting": {
            "check_consolidation": "All bills on single check (hide extra stub detail)",
            "check_stub_breakdown": "List each bill detail line item (expanded view)",
            "hold_payments": false,
            "email_echeck_receipt": true,
            "payment_terms": null,
            "default_check_memo": null,
            "default_gl_account": null,
            "work_order_adjustment_percent": 0,
            "discount": null,
            "online_payables_enabled": false,
            "payment_type": "Check",
            "bank_routing_number": null,
            "bank_account_number": null,
            "savings_account": false
        },
        "compliance": {
            "workers_comp_expiration": null,
            "general_liability_expiration": "2026-07-11",
            "epa_certification_expiration": null,
            "auto_insurance_expiration": null,
            "state_license_expiration": null,
            "contract_expiration": null,
            "request_compliance_documents_cta": true
        },
        "paymentMethod": "Check",
        "send1099": true,
        "notes": [
            {
                "posted_by": "Lisa Zohoury",
                "ts": "2024-10-19 10:37:05 AM",
                "body": "@Candice.Palacio request for W-9 and COI for Workers' Comp Insurance. If exempt, need written statement from Board of WC. Current COI does not show Southeastern Apartment Investment Corp as 'additional insured' — needs correction."
            },
            {
                "posted_by": "Lisa Zohoury",
                "ts": "2024-01-17 12:40:13 PM",
                "body": "Did not send 1099 since paid with Zelle."
            }
        ],
        "source": "appfolio-vendor-detail-2716"
    },
    {
        "id": "appfolio-v-p1-1",
        "name": "1-800-GOT-JUNK?",
        "primaryContactName": null,
        "website": null,
        "vendorType": null,
        "phoneType": null,
        "phone": "(555) 555-XXXX",
        "phoneNotes": null,
        "emails": [],
        "primaryAddress": null,
        "vendorPortalActivated": false,
        "federalTax": null,
        "accounting": null,
        "compliance": null,
        "paymentMethod": null,
        "send1099": false,
        "notes": [],
        "source": "appfolio-vendors-page1"
    },
    {
        "id": "appfolio-v-p1-2",
        "name": "1001 NIGHTS PERSIAN",
        "primaryContactName": null,
        "website": null,
        "vendorType": null,
        "phoneType": null,
        "phone": "(555) 555-XXXX",
        "phoneNotes": null,
        "emails": [],
        "primaryAddress": null,
        "vendorPortalActivated": false,
        "federalTax": null,
        "accounting": null,
        "compliance": null,
        "paymentMethod": null,
        "send1099": false,
        "notes": [],
        "source": "appfolio-vendors-page1"
    },
    {
        "id": "appfolio-v-p1-3",
        "name": "10129 CAVA NORTH BUCKHEAD",
        "primaryContactName": null,
        "website": null,
        "vendorType": null,
        "phoneType": null,
        "phone": null,
        "phoneNotes": null,
        "emails": [],
        "primaryAddress": null,
        "vendorPortalActivated": false,
        "federalTax": null,
        "accounting": null,
        "compliance": null,
        "paymentMethod": null,
        "send1099": false,
        "notes": [],
        "source": "appfolio-vendors-page1"
    },
    {
        "id": "appfolio-v-p1-4",
        "name": "12 OAKS PARKING, LLC",
        "primaryContactName": null,
        "website": null,
        "vendorType": null,
        "phoneType": null,
        "phone": null,
        "phoneNotes": null,
        "emails": [],
        "primaryAddress": null,
        "vendorPortalActivated": false,
        "federalTax": null,
        "accounting": null,
        "compliance": null,
        "paymentMethod": null,
        "send1099": false,
        "notes": [],
        "source": "appfolio-vendors-page1"
    },
    {
        "id": "appfolio-v-p1-5",
        "name": "2-STORY TECHNICAL ROOFING LLC",
        "primaryContactName": null,
        "website": null,
        "vendorType": null,
        "phoneType": null,
        "phone": "(555) 555-XXXX",
        "phoneNotes": null,
        "emails": [],
        "primaryAddress": null,
        "vendorPortalActivated": false,
        "federalTax": null,
        "accounting": null,
        "compliance": null,
        "paymentMethod": null,
        "send1099": false,
        "notes": [],
        "source": "appfolio-vendors-page1"
    },
    {
        "id": "appfolio-v-p1-6",
        "name": "201 CONTRACTING CO.",
        "primaryContactName": null,
        "website": null,
        "vendorType": null,
        "phoneType": null,
        "phone": null,
        "phoneNotes": null,
        "emails": [],
        "primaryAddress": null,
        "vendorPortalActivated": false,
        "federalTax": null,
        "accounting": null,
        "compliance": null,
        "paymentMethod": null,
        "send1099": false,
        "notes": [],
        "source": "appfolio-vendors-page1"
    },
    {
        "id": "appfolio-v-p1-7",
        "name": "404GUTTERS",
        "primaryContactName": null,
        "website": null,
        "vendorType": null,
        "phoneType": null,
        "phone": "(555) 555-XXXX",
        "phoneNotes": null,
        "emails": [],
        "primaryAddress": null,
        "vendorPortalActivated": false,
        "federalTax": null,
        "accounting": null,
        "compliance": null,
        "paymentMethod": null,
        "send1099": false,
        "notes": [],
        "source": "appfolio-vendors-page1"
    },
    {
        "id": "appfolio-v-p1-8",
        "name": "888-COOL",
        "primaryContactName": null,
        "website": null,
        "vendorType": null,
        "phoneType": null,
        "phone": "(555) 555-XXXX",
        "phoneNotes": null,
        "emails": [],
        "primaryAddress": null,
        "vendorPortalActivated": false,
        "federalTax": null,
        "accounting": null,
        "compliance": null,
        "paymentMethod": null,
        "send1099": false,
        "notes": [],
        "source": "appfolio-vendors-page1"
    }
] : [];
export const APPFOLIO_VENDOR_TOTAL = 3040;
