/**
 * AppFolio-derived fixture — workorders
 *
 * GENERATED by Scripts/derive_appfolio_fixtures.mjs — DO NOT EDIT BY HAND.
 * Source: AppFolio_Screenshots/data/*.json (captured 2026-04-19).
 *
 * Gated by VITE_APPFOLIO_SEEDS per GR-7. When flag is false this module
 * exports empty arrays so no real-person data leaks into public builds.
 */
/* eslint-disable */

const ENABLED = (import.meta as any).env?.VITE_APPFOLIO_SEEDS !== 'false';

export interface AppfolioResidentAvailability { day: string; startTime?: string; endTime?: string; notes?: string }
export interface AppfolioActionLogEntry { ts: string; actor: string; event?: string; action?: string; detail?: string }
export interface AppfolioWorkOrder {
    id: string; number: string | null;
    workOrderId: number | null; serviceRequestId: number | null;
    jobDescription: string | null; priority: string | null; status: string;
    property: string | null; unit: string | null; resident: string | null;
    residentAvailability: AppfolioResidentAvailability[];
    actionsLog: AppfolioActionLogEntry[];
    owner: string | null; permissionToEnter: boolean;
    vendorTrade: string | null; vendorInstructions: string | null;
    source: string;
}
export const APPFOLIO_WORK_ORDERS: AppfolioWorkOrder[] = ENABLED ? [
    {
        "id": "appfolio-wo-19511",
        "number": "19511-1",
        "workOrderId": 19523,
        "serviceRequestId": 19511,
        "jobDescription": "Fire alarm needs replaced. Beeping and can't reach.",
        "priority": "Normal",
        "status": "New",
        "property": "Woodland Parc Townhomes",
        "unit": "2789-1-4",
        "resident": "Brianna M. Jackson",
        "residentAvailability": [
            {
                "day": "2026-04-20",
                "startTime": "8:00am",
                "endTime": "12:00pm"
            },
            {
                "day": "2026-04-20",
                "startTime": "10:00am",
                "endTime": "2:00pm"
            },
            {
                "day": "2026-04-20",
                "startTime": "1:00pm",
                "endTime": "5:00pm"
            }
        ],
        "actionsLog": [
            {
                "ts": "2026-04-17 08:24 PM",
                "actor": "System",
                "event": "Resident submitted preferred times",
                "detail": "04/20/2026 at 08:00AM-12:00PM EDT, 10:00AM-02:00PM EDT, 01:00PM-05:00PM EDT"
            },
            {
                "ts": "2026-04-17 08:24 PM",
                "actor": "Brianna M. Jackson",
                "event": "Submitted online"
            }
        ],
        "owner": "Southeastern Apartment Investment Corp",
        "permissionToEnter": false,
        "vendorTrade": null,
        "vendorInstructions": null,
        "source": "appfolio-wo-detail-19511"
    },
    {
        "id": "appfolio-wo-p1-1",
        "number": null,
        "workOrderId": null,
        "serviceRequestId": null,
        "jobDescription": "Fire alarm needs replaced. Beeping and can't reach.",
        "priority": null,
        "status": "New",
        "property": "Woodland Parc Townhomes",
        "unit": "2789-1",
        "resident": null,
        "residentAvailability": [],
        "actionsLog": [],
        "owner": null,
        "permissionToEnter": false,
        "vendorTrade": null,
        "vendorInstructions": null,
        "source": "appfolio-work-orders-page1"
    },
    {
        "id": "appfolio-wo-p1-2",
        "number": null,
        "workOrderId": null,
        "serviceRequestId": null,
        "jobDescription": "Plug outlet not working in first bedroom and window does not open. Install knob on kitchen drawer.",
        "priority": null,
        "status": "New",
        "property": "Riverwood Club Apartments",
        "unit": "C06",
        "resident": null,
        "residentAvailability": [],
        "actionsLog": [],
        "owner": null,
        "permissionToEnter": false,
        "vendorTrade": null,
        "vendorInstructions": null,
        "source": "appfolio-work-orders-page1"
    },
    {
        "id": "appfolio-wo-p1-3",
        "number": null,
        "workOrderId": null,
        "serviceRequestId": null,
        "jobDescription": "All of the plugs in the kitchen are not working.",
        "priority": null,
        "status": "New",
        "property": "Riverwood Club Apartments",
        "unit": "D13",
        "resident": null,
        "residentAvailability": [],
        "actionsLog": [],
        "owner": null,
        "permissionToEnter": false,
        "vendorTrade": null,
        "vendorInstructions": null,
        "source": "appfolio-work-orders-page1"
    },
    {
        "id": "appfolio-wo-p1-4",
        "number": null,
        "workOrderId": null,
        "serviceRequestId": null,
        "jobDescription": "Ac water reservoir is full of water and overflowing",
        "priority": null,
        "status": "New",
        "property": "Riverwood Club Apartments",
        "unit": "H04",
        "resident": null,
        "residentAvailability": [],
        "actionsLog": [],
        "owner": null,
        "permissionToEnter": false,
        "vendorTrade": null,
        "vendorInstructions": null,
        "source": "appfolio-work-orders-page1"
    },
    {
        "id": "appfolio-wo-p1-5",
        "number": null,
        "workOrderId": null,
        "serviceRequestId": null,
        "jobDescription": "Repair the stove vent.",
        "priority": null,
        "status": "New",
        "property": "Riverwood Club Apartments",
        "unit": "C15",
        "resident": null,
        "residentAvailability": [],
        "actionsLog": [],
        "owner": null,
        "permissionToEnter": false,
        "vendorTrade": null,
        "vendorInstructions": null,
        "source": "appfolio-work-orders-page1"
    },
    {
        "id": "appfolio-wo-p1-6",
        "number": null,
        "workOrderId": null,
        "serviceRequestId": null,
        "jobDescription": "A/C blowing out hot air.",
        "priority": null,
        "status": "New",
        "property": "Riverwood Club Apartments",
        "unit": "H01",
        "resident": null,
        "residentAvailability": [],
        "actionsLog": [],
        "owner": null,
        "permissionToEnter": false,
        "vendorTrade": null,
        "vendorInstructions": null,
        "source": "appfolio-work-orders-page1"
    },
    {
        "id": "appfolio-wo-p1-7",
        "number": null,
        "workOrderId": null,
        "serviceRequestId": null,
        "jobDescription": "Microwave light (shining down on the stove, not inside the microwave) went out.",
        "priority": null,
        "status": "New",
        "property": "Woodland Parc Townhomes",
        "unit": "2838-4",
        "resident": null,
        "residentAvailability": [],
        "actionsLog": [],
        "owner": null,
        "permissionToEnter": false,
        "vendorTrade": null,
        "vendorInstructions": null,
        "source": "appfolio-work-orders-page1"
    },
    {
        "id": "appfolio-wo-p1-8",
        "number": null,
        "workOrderId": null,
        "serviceRequestId": null,
        "jobDescription": "Replace sheetrock from leak 2 weeks ago",
        "priority": null,
        "status": "Assigned",
        "property": "Woodland Parc Townhomes",
        "unit": "2767-3",
        "resident": null,
        "residentAvailability": [],
        "actionsLog": [],
        "owner": null,
        "permissionToEnter": false,
        "vendorTrade": null,
        "vendorInstructions": null,
        "source": "appfolio-work-orders-page1"
    },
    {
        "id": "appfolio-wo-p1-9",
        "number": null,
        "workOrderId": null,
        "serviceRequestId": null,
        "jobDescription": null,
        "priority": null,
        "status": "Assigned",
        "property": "2070 AZALEA DRIVE",
        "unit": null,
        "resident": null,
        "residentAvailability": [],
        "actionsLog": [],
        "owner": null,
        "permissionToEnter": false,
        "vendorTrade": null,
        "vendorInstructions": null,
        "source": "appfolio-work-orders-page1"
    },
    {
        "id": "appfolio-wo-p1-10",
        "number": null,
        "workOrderId": null,
        "serviceRequestId": null,
        "jobDescription": "Kitchen sink faucet is extremely loose. Maintenance noticed it while here and stated to put in an additional request so this can be completed when coming back to paint over ceiling leak.",
        "priority": null,
        "status": "Assigned",
        "property": "Woodland Parc Townhomes",
        "unit": "2763-3",
        "resident": null,
        "residentAvailability": [],
        "actionsLog": [],
        "owner": null,
        "permissionToEnter": false,
        "vendorTrade": null,
        "vendorInstructions": null,
        "source": "appfolio-work-orders-page1"
    },
    {
        "id": "appfolio-wo-p1-11",
        "number": null,
        "workOrderId": null,
        "serviceRequestId": null,
        "jobDescription": "Yellow jackets getting inside house.",
        "priority": null,
        "status": "New",
        "property": "Wieuca Property",
        "unit": null,
        "resident": null,
        "residentAvailability": [],
        "actionsLog": [],
        "owner": null,
        "permissionToEnter": false,
        "vendorTrade": null,
        "vendorInstructions": null,
        "source": "appfolio-work-orders-page1"
    },
    {
        "id": "appfolio-wo-p1-12",
        "number": null,
        "workOrderId": null,
        "serviceRequestId": null,
        "jobDescription": "Dishwasher Friction Pad Sleeves came off so dishwasher has a hard time staying closed.",
        "priority": null,
        "status": "Work Done",
        "property": "Woodland Parc Townhomes",
        "unit": "2771-2",
        "resident": null,
        "residentAvailability": [],
        "actionsLog": [],
        "owner": null,
        "permissionToEnter": false,
        "vendorTrade": null,
        "vendorInstructions": null,
        "source": "appfolio-work-orders-page1"
    },
    {
        "id": "appfolio-wo-p1-13",
        "number": null,
        "workOrderId": null,
        "serviceRequestId": null,
        "jobDescription": "Floor dipping and cracking.",
        "priority": null,
        "status": "Waiting",
        "property": "Riverwood Club Apartments",
        "unit": "C15",
        "resident": null,
        "residentAvailability": [],
        "actionsLog": [],
        "owner": null,
        "permissionToEnter": false,
        "vendorTrade": null,
        "vendorInstructions": null,
        "source": "appfolio-work-orders-page1"
    }
] : [];
export const APPFOLIO_WORK_ORDER_TOTAL = 1563;
