/**
 * templateGeneratorStore — SSR-safe per-user store for the Template
 * Generator widget's templates (HTML source + per-key variable values/types).
 *
 * Per-USER, dynamic key `dwellium:templateGenerator:<uid>` (holder
 * `templateGeneratorUserIdHolder`, written by the perUserIdentity single
 * writer) + One Save `withSync('templateGenerator')` — universalShellStore
 * sister shape (plan 058) — so templates follow the account to any machine.
 *
 * Mirrors the established createLocalStorageStore + useSyncExternalStore
 * pattern (see universalShellStore.ts / docs/code.md 2026-09-17). Read via
 * the useTemplateGeneratorState() hook; write via setTemplateGeneratorState().
 */
import { useSyncExternalStore } from 'react';
import { createLocalStorageStore } from './createLocalStorageStore';
import { withSync } from '../lib/oneSaveStore';
import { templateGeneratorUserIdHolder, usePerUserIdentity } from '../lib/perUserIdentity';
import type { VarType } from '../components/DocViewer/templateEngine';

export interface StoredTemplate {
    id: string;
    name: string;
    html: string;
    values: Record<string, string>;
    types: Record<string, VarType>;
}

export interface TemplateGeneratorState {
    templates: StoredTemplate[];
    activeId: string;
}

/** Per-user key prefix. Full key is `${TEMPLATE_GENERATOR_KEY}:<uid>` or `:_anonymous`. */
export const TEMPLATE_GENERATOR_KEY = 'dwellium:templateGenerator';

/** Today's layout (TemplateGenerator.tsx), violet swapped for neutral ink + a Dwellium footer. No sample values. */
export const DEFAULT_HTML_TEMPLATE = `<!DOCTYPE html>
<html>
<head>
  <style>
    body { font-family: 'Helvetica', sans-serif; padding: 40px; color: #1a1a2e; }
    h1 { color: #111; font-size: 28px; border-bottom: 2px solid #999; padding-bottom: 8px; }
    .section { margin: 20px 0; }
    .label { font-weight: bold; color: #636e72; font-size: 12px; text-transform: uppercase; letter-spacing: 1px; }
    .value { font-size: 16px; margin-top: 4px; }
    table { width: 100%; border-collapse: collapse; margin: 20px 0; }
    th { background: #111; color: white; padding: 10px; text-align: left; }
    td { padding: 10px; border-bottom: 1px solid #dfe6e9; }
    .footer { margin-top: 40px; font-size: 11px; color: #b2bec3; text-align: center; }
  </style>
</head>
<body>
  <h1>{{title}}</h1>
  <div class="section">
    <div class="label">Prepared For</div>
    <div class="value">{{client_name}}</div>
  </div>
  <div class="section">
    <div class="label">Property</div>
    <div class="value">{{property_address}}</div>
  </div>
  <div class="section">
    <div class="label">Date</div>
    <div class="value">{{date}}</div>
  </div>
  <table>
    <tr><th>Item</th><th>Description</th><th>Amount</th></tr>
    <tr><td>{{item_1}}</td><td>{{desc_1}}</td><td>{{amount_1}}</td></tr>
    <tr><td>{{item_2}}</td><td>{{desc_2}}</td><td>{{amount_2}}</td></tr>
  </table>
  <div class="footer">Generated by Dwellium · {{date}}</div>
</body>
</html>`;

export function createDefaultState(): TemplateGeneratorState {
    return {
        templates: [{ id: 'default', name: 'Property report', html: DEFAULT_HTML_TEMPLATE, values: {}, types: {} }],
        activeId: 'default',
    };
}

function resolveKey(): string {
    return `${TEMPLATE_GENERATOR_KEY}:${templateGeneratorUserIdHolder.current ?? '_anonymous'}`;
}

const VAR_TYPES: readonly VarType[] = ['text', 'number', 'date', 'currency'];

function isStringRecord(v: unknown): v is Record<string, string> {
    return v != null && typeof v === 'object' && !Array.isArray(v)
        && Object.values(v as Record<string, unknown>).every((x) => typeof x === 'string');
}

function isVarTypeRecord(v: unknown): v is Record<string, VarType> {
    return v != null && typeof v === 'object' && !Array.isArray(v)
        && Object.values(v as Record<string, unknown>).every((x) => (VAR_TYPES as readonly string[]).includes(x as string));
}

/** Validates one template shape field by field — a malformed entry is dropped, not the whole list. */
function isStoredTemplate(v: unknown): v is StoredTemplate {
    if (v == null || typeof v !== 'object') return false;
    const t = v as Record<string, unknown>;
    return typeof t.id === 'string' && t.id.length > 0
        && typeof t.name === 'string'
        && typeof t.html === 'string'
        && isStringRecord(t.values)
        && isVarTypeRecord(t.types);
}

function deserialize(raw: string | null): TemplateGeneratorState {
    if (raw == null) return createDefaultState();
    try {
        const parsed = JSON.parse(raw) as { templates?: unknown; activeId?: unknown } | null;
        if (parsed == null || typeof parsed !== 'object' || !Array.isArray(parsed.templates)) return createDefaultState();
        const templates = parsed.templates.filter(isStoredTemplate);
        if (templates.length === 0) return createDefaultState();
        const activeId = typeof parsed.activeId === 'string' && templates.some((t) => t.id === parsed.activeId)
            ? parsed.activeId
            : templates[0].id;
        return { templates, activeId };
    } catch {
        return createDefaultState();
    }
}

export const templateGeneratorStore = withSync(
    createLocalStorageStore<TemplateGeneratorState>({ key: resolveKey, deserializer: deserialize, defaultValue: createDefaultState() }),
    { objectType: 'templateGenerator', holder: templateGeneratorUserIdHolder, resolveKey },
);

/** Replace the stored state and notify subscribers (caller owns merging — e.g. one template's values). */
export function setTemplateGeneratorState(next: TemplateGeneratorState): void {
    templateGeneratorStore.set(next, () => {
        try { localStorage.setItem(resolveKey(), JSON.stringify(next)); } catch { /* quota / sandboxed — keep typing */ }
    });
}

/** Read the current + subscribe to changes. SSR-safe. */
export function useTemplateGeneratorState(): TemplateGeneratorState {
    usePerUserIdentity(); // single writer — resolve this render's user.id into every holder first
    return useSyncExternalStore(
        templateGeneratorStore.subscribe,
        templateGeneratorStore.getSnapshot,
        templateGeneratorStore.getServerSnapshot,
    );
}
