/**
 * artifactStore — P12-3 (gap item 10, the video's headline build,
 * 2026-06-12): "we build beautiful things with the agent and invariably we
 * LOSE them." Every substantial agent output (ARA long-form replies, team-run
 * deliverables, generated images, drafted documents) is auto-captured here —
 * typed, titled (≤5 words), summarized (≤14 words, the video's exact spec) —
 * and browsable in the Artifact Gallery widget: filter, search, preview,
 * pin, delete.
 *
 * Storage: per-user dynamic-key factory + One Save ('artifacts'), tabGroup
 * sister shape incl. `.reset()`. Bounded: 120 artifacts, 400k chars each
 * (images ride as data URLs; oversized content is truncated with a note).
 */
import { useContext, useSyncExternalStore } from 'react';
import { createLocalStorageStore } from '../utils/createLocalStorageStore';
import { withSync } from './oneSaveStore';
import { UserContext } from '../context/UserContext';

export type ArtifactType = 'markdown' | 'html' | 'image' | 'code' | 'data' | 'text';
export type ArtifactSource = 'ara' | 'team-run' | 'skill' | 'stella' | 'manual';

export interface Artifact {
    id: string;
    type: ArtifactType;
    /** ≤5 words. */
    title: string;
    /** ≤14 words. */
    summary: string;
    /** Text content, or a data URL for images. */
    content: string;
    source: ArtifactSource;
    pinned?: boolean;
    createdAt: number;
}

const MAX_ARTIFACTS = 120;
const MAX_CONTENT = 400_000;

import { integrationsUserIdHolder } from '../utils/integrationsStore';

/** Shared identity with the integrations bundle — always set while authed. */
export const artifactsUserIdHolder = integrationsUserIdHolder;

function resolveKey(): string {
    const uid = artifactsUserIdHolder.current;
    return uid ? `artifacts:${uid}` : 'artifacts:_anonymous';
}

function isArtifact(a: unknown): a is Artifact {
    return !!a && typeof (a as Artifact).id === 'string' && typeof (a as Artifact).content === 'string';
}

function deserialize(raw: string | null): Artifact[] {
    if (!raw) return [];
    try {
        const parsed = JSON.parse(raw);
        return Array.isArray(parsed) ? parsed.filter(isArtifact).slice(-MAX_ARTIFACTS) : [];
    } catch {
        return [];
    }
}

export const artifactStore = withSync(
    createLocalStorageStore<Artifact[]>({
        key: resolveKey,
        deserializer: deserialize,
        defaultValue: [],
    }),
    { objectType: 'artifacts', holder: artifactsUserIdHolder, resolveKey },
);

function persist(next: Artifact[]): void {
    artifactStore.set(next, () => {
        try { localStorage.setItem(resolveKey(), JSON.stringify(next)); } catch { /* full/sandboxed */ }
    });
}

/* ─── Type detection + auto title/summary ─── */

export function detectType(content: string): ArtifactType {
    const c = content.trimStart();
    if (c.startsWith('data:image/')) return 'image';
    if (/^<!doctype html|^<html|^<svg/i.test(c)) return 'html';
    if (/^\s*[{[]/.test(c) && (() => { try { JSON.parse(c); return true; } catch { return false; } })()) return 'data';
    if (/^```|^(?:import|export|function|const|class|def|public|#include)\b/m.test(c.slice(0, 400))) return 'code';
    if (/^#{1,3}\s|\n#{1,3}\s|\n- |\n\* |\n\d+\. |\*\*[^*]+\*\*/.test(c.slice(0, 1200))) return 'markdown';
    return 'text';
}

const STOP_TITLE = /^(?:here(?:'s| is)|sure|okay|certainly|below is|i've|this is)\b[,:]?\s*/i;

/** ≤5 words, from the first heading/line (video spec: "fiveword overview"). */
export function autoTitle(content: string, type: ArtifactType): string {
    if (type === 'image') return 'Generated image';
    const heading = content.match(/^#{1,3}\s+(.{3,80})$/m)?.[1];
    const base = (heading ?? content.split('\n').find(l => l.trim().length > 2) ?? 'Untitled')
        .replace(STOP_TITLE, '')
        .replace(/[#*`>\[\]|]/g, ' ')
        .trim();
    return base.split(/\s+/).slice(0, 5).join(' ').slice(0, 60) || 'Untitled';
}

/** ≤14 words (video spec: "no more than 13 to 14 words underneath"). */
export function autoSummary(content: string, type: ArtifactType): string {
    if (type === 'image') return 'Image generated by an agent.';
    const flat = content.replace(/^#{1,3}\s+.*$/m, '').replace(/[#*`>|]/g, ' ').replace(/\s+/g, ' ').trim();
    return flat.split(/\s+/).slice(0, 14).join(' ').slice(0, 140);
}

/* ─── Mutators ─── */

function newArtifactId(): string {
    return `art-${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 6)}`;
}

/**
 * Record an agent output. Never throws (called from chat/skill paths).
 * Returns the artifact, or null when content is empty/duplicate-of-last.
 */
export function recordArtifact(input: { content: string; source: ArtifactSource; title?: string; type?: ArtifactType }): Artifact | null {
    try {
        const raw = (input.content ?? '').trim();
        if (!raw) return null;
        const cur = artifactStore.getSnapshot();
        const last = cur[cur.length - 1];
        if (last && last.content === raw.slice(0, MAX_CONTENT)) return null; // dedupe immediate repeats
        const type = input.type ?? detectType(raw);
        const content = raw.length > MAX_CONTENT
            ? `${raw.slice(0, MAX_CONTENT)}\n\n[Truncated: ${raw.length.toLocaleString()} chars total]`
            : raw;
        const artifact: Artifact = {
            id: newArtifactId(),
            type,
            title: (input.title?.trim() || autoTitle(raw, type)),
            summary: autoSummary(raw, type),
            content,
            source: input.source,
            createdAt: Date.now(),
        };
        // Pinned artifacts survive the cap.
        const next = [...cur, artifact];
        if (next.length > MAX_ARTIFACTS) {
            const pinned = next.filter(a => a.pinned);
            const rest = next.filter(a => !a.pinned).slice(-(MAX_ARTIFACTS - pinned.length));
            persist([...pinned, ...rest].sort((a, b) => a.createdAt - b.createdAt));
        } else {
            persist(next);
        }
        return artifact;
    } catch {
        return null;
    }
}

export function deleteArtifact(id: string): void {
    persist(artifactStore.getSnapshot().filter(a => a.id !== id));
}

export function togglePinArtifact(id: string): void {
    persist(artifactStore.getSnapshot().map(a => (a.id === id ? { ...a, pinned: !a.pinned } : a)));
}

export function clearArtifacts(): void {
    persist([]);
}

export function resetArtifacts(): void {
    artifactStore.set([], () => {
        try { localStorage.removeItem(resolveKey()); } catch { /* sandboxed */ }
    });
}

/**
 * Auto-capture heuristic for chat replies: only SUBSTANTIAL outputs become
 * artifacts (long-form, or clearly structured documents/code) — chat
 * small-talk never lands in the gallery.
 */
export function isSubstantialOutput(text: string): boolean {
    const t = (text ?? '').trim();
    if (t.length < 700) return /^data:image\//.test(t); // short → only images qualify
    return true;
}

/* ─── Hook ─── */

export function useArtifacts() {
    const userCtx = useContext(UserContext);
    artifactsUserIdHolder.current = userCtx?.user?.id ?? artifactsUserIdHolder.current ?? null;
    const artifacts = useSyncExternalStore(
        artifactStore.subscribe,
        artifactStore.getSnapshot,
        artifactStore.getServerSnapshot,
    );
    return { artifacts, deleteArtifact, togglePinArtifact, clearArtifacts, recordArtifact };
}
