/**
 * TokenSaver — shows whether the token-saver skill is active, Claude Code's
 * prompt-cache reuse (not a skill effect), and the skill's own trimming. All figures are ESTIMATES, read at runtime from
 * /token-saver-stats.json (regenerated by
 * .claude/skills/token-saver/scripts/token_saver_stats.py) — never hard-coded.
 * Sibling of AiSpend; same estimate-and-label-it discipline.
 *
 * DEV/LOCAL ONLY: registered only when import.meta.env.DEV (widgetRegistry.ts);
 * the stats file is a machine-local snapshot and is not tracked in git.
 */
import { useEffect, useState } from 'react';
import { Zap, ShieldCheck, ShieldOff, RotateCw } from 'lucide-react';
import './TokenSaver.css';

// Every field is optional: the file is hand-regenerated and may be older or
// newer than this component. Numbers are coerced with num() before use.
interface TokenSaverStats {
    generated_at?: string;
    scope_label?: string;
    skill?: { active?: boolean; name?: string; path?: string };
    totals?: {
        sessions?: number;
        model_calls?: number;
        fresh_input_tokens?: number;
        cache_read_tokens?: number;
        cache_creation_tokens?: number;
        output_tokens?: number;
        billed_input_equivalent?: number;
    };
    savings?: {
        cache_reuse_tokens_saved?: number;
        delegation_tokens_offloaded?: number;
        total_estimated_tokens_saved?: number;
        estimated_usd_saved?: number;
        baseline_note?: string;
        confidence?: string;
    };
    skill_effect?: {
        packets?: number;
        source_bytes?: number;
        packet_bytes?: number;
        est_tokens_trimmed?: number;
        basis?: string;
    };
}

type LoadError = 'missing' | 'malformed';

const STATS_URL = '/token-saver-stats.json'; // absolute: catch-all routes break relative paths
const STALE_MS = 7 * 24 * 60 * 60 * 1000;

const num = (v: unknown) => {
    const n = Number(v);
    return Number.isFinite(n) ? n : 0;
};
const abbrev = (v: number) => {
    if (Math.abs(v) >= 1e9) return `${(v / 1e9).toFixed(1)}B`;
    if (Math.abs(v) >= 1e6) return `${(v / 1e6).toFixed(1)}M`;
    if (Math.abs(v) >= 1e3) return `${(v / 1e3).toFixed(1)}k`;
    return String(v);
};
const fmt$ = (v: number) => `$${v.toLocaleString(undefined, {
    minimumFractionDigits: 2, maximumFractionDigits: 2,
})}`;

async function loadStats(): Promise<TokenSaverStats> {
    const r = await fetch(STATS_URL, { cache: 'no-store' });
    if (!r.ok) throw new Error('missing');
    const text = await r.text();
    let d: unknown;
    try {
        d = JSON.parse(text);
    } catch {
        // An SPA fallback serves index.html (200) for a missing file.
        throw new Error(text.trimStart().startsWith('<') ? 'missing' : 'malformed');
    }
    if (!d || typeof d !== 'object' || Array.isArray(d)) throw new Error('malformed');
    return d as TokenSaverStats;
}

const R = 54;
const CIRC = 2 * Math.PI * R;

export default function TokenSaver() {
    const [stats, setStats] = useState<TokenSaverStats | null>(null);
    const [error, setError] = useState<LoadError | null>(null);
    const [mounted, setMounted] = useState(false);
    const [attempt, setAttempt] = useState(0);

    useEffect(() => {
        let cancelled = false;
        setError(null);
        setStats(null);
        loadStats()
            .then(d => { if (!cancelled) { setStats(d); requestAnimationFrame(() => setMounted(true)); } })
            .catch((e: unknown) => { if (!cancelled) setError(e instanceof Error && e.message === 'malformed' ? 'malformed' : 'missing'); });
        return () => { cancelled = true; };
    }, [attempt]);

    if (error) {
        return (
            <div className="tsv" role="alert">
                <p className="tsv-muted">
                    {error === 'missing'
                        ? 'Token Saver stats file not found. Run token_saver_stats.py to generate it.'
                        : 'Token Saver stats file is malformed (not a JSON object).'}
                </p>
                <button type="button" className="tsv-retry" onClick={() => setAttempt(a => a + 1)}>
                    <RotateCw size={12} /> Retry
                </button>
            </div>
        );
    }
    if (!stats) return <div className="tsv tsv-muted">Loading Token Saver…</div>;

    const active = stats.skill?.active === true;
    const t = stats.totals ?? {};
    const s = stats.savings ?? {};
    const measured = s.confidence === 'measured';

    const generated = new Date(stats.generated_at ?? '');
    const validDate = !Number.isNaN(generated.getTime());
    const stale = !validDate || Date.now() - generated.getTime() > STALE_MS;
    const asOf = validDate
        ? generated.toLocaleString(undefined, { dateStyle: 'short', timeStyle: 'short' })
        : 'unknown date';

    const cacheRead = num(t.cache_read_tokens);
    const totalInput = num(t.fresh_input_tokens) + cacheRead + num(t.cache_creation_tokens);
    const pct = totalInput > 0 ? Math.max(0, Math.min(100, (cacheRead / totalInput) * 100)) : 0;
    const cache = num(s.cache_reuse_tokens_saved);
    const deleg = num(s.delegation_tokens_offloaded);
    const mx = Math.max(cache, deleg, 1);
    const packets = num(stats.skill_effect?.packets);
    const trimmed = num(stats.skill_effect?.est_tokens_trimmed);

    const bar = (label: string, value: number) => (
        <div className="tsv-bar">
            <div className="tsv-barmeta"><span>{label}</span><span>{value.toLocaleString()}</span></div>
            <div
                className="tsv-track2" role="meter" aria-label={label}
                aria-valuemin={0} aria-valuemax={mx} aria-valuenow={value}
            >
                <div className="tsv-fill2" style={{ width: `${(value / mx) * 100}%` }} />
            </div>
        </div>
    );

    return (
        <div className={`tsv${stale ? ' tsv-stale' : ''}`}>
            <header className="tsv-head">
                <h3><Zap size={15} /> Token Saver</h3>
                <span className={`tsv-pill ${active ? 'on' : 'off'}`}>
                    {active ? <ShieldCheck size={12} /> : <ShieldOff size={12} />}
                    {active ? 'ACTIVE' : 'INACTIVE'}
                </span>
            </header>
            <p className="tsv-asof">
                as of {asOf}
                {stale && <span className="tsv-stale-tag">stale</span>}
            </p>

            {!measured ? (
                <p className="tsv-muted">
                    {active
                        ? 'Skill installed — no sessions measured in this scope yet.'
                        : 'Skill not installed.'}
                </p>
            ) : (
                <div className="tsv-data">
                    <div className="tsv-hero">
                        <div className="tsv-ringbox">
                            <svg
                                width="128" height="128" viewBox="0 0 128 128" className="tsv-ring"
                                role="img" aria-label={`${Math.round(pct)}% of input served from cache`}
                            >
                                <circle cx="64" cy="64" r={R} fill="none" strokeWidth="10" className="tsv-track" />
                                <circle
                                    cx="64" cy="64" r={R} fill="none" strokeWidth="10" strokeLinecap="round"
                                    className="tsv-fill"
                                    strokeDasharray={CIRC}
                                    strokeDashoffset={mounted ? CIRC * (1 - pct / 100) : CIRC}
                                />
                            </svg>
                            <div className="tsv-ctr">
                                <strong>{abbrev(cacheRead)}</strong>
                                <small>{cacheRead.toLocaleString()}</small>
                                <em>tokens reused from prompt cache</em>
                            </div>
                        </div>
                        <div className="tsv-money">
                            <strong>{fmt$(num(s.estimated_usd_saved))}</strong>
                            <em>est. cache value</em>
                            <span>{pct.toFixed(1)}% of input from cache · {num(t.model_calls).toLocaleString()} calls</span>
                        </div>
                    </div>

                    <div className="tsv-bars">
                        {bar('Prompt-cache reuse', cache)}
                        {deleg > 0 && bar('Worker tokens (delegated)', deleg)}
                    </div>
                    {packets > 0 && (
                        <p className="tsv-skill">
                            Skill: {packets.toLocaleString()} packets · ~{trimmed.toLocaleString()} tokens trimmed (est., all projects)
                        </p>
                    )}
                </div>
            )}

            {s.baseline_note && <p className="tsv-note">{s.baseline_note}</p>}
        </div>
    );
}
