/**
 * TokenSaver — shows whether the token-saver skill is active and how much it
 * has saved. All figures are ESTIMATES, read at runtime from
 * /token-saver-stats.json (regenerated by
 * .claude/skills/token-saver/scripts/token_saver_stats.py) — never hard-coded.
 * Sibling of AiSpend; same estimate-and-label-it discipline.
 */
import { useEffect, useState } from 'react';
import { Zap, ShieldCheck, ShieldOff } from 'lucide-react';
import './TokenSaver.css';

interface TokenSaverStats {
    scope_label: string;
    skill: { active: boolean; path: string };
    totals: {
        sessions: number;
        model_calls: number;
        fresh_input_tokens: number;
        cache_read_tokens: number;
        output_tokens: number;
        billed_input_equivalent: number;
    };
    savings: {
        cache_reuse_tokens_saved: number;
        delegation_tokens_offloaded: number;
        total_estimated_tokens_saved: number;
        estimated_usd_saved: number;
        baseline_note: string;
        confidence: string;
    };
}

const abbrev = (n: number) => {
    const v = Number(n) || 0;
    if (Math.abs(v) >= 1e9) return `${(v / 1e9).toFixed(1)}B`;
    if (Math.abs(v) >= 1e6) return `${(v / 1e6).toFixed(1)}M`;
    if (Math.abs(v) >= 1e3) return `${(v / 1e3).toFixed(1)}k`;
    return String(v);
};
const fmt$ = (n: number) => `$${(Number(n) || 0).toLocaleString(undefined, {
    minimumFractionDigits: 2, maximumFractionDigits: 2,
})}`;

const R = 54;
const CIRC = 2 * Math.PI * R;

export default function TokenSaver() {
    const [stats, setStats] = useState<TokenSaverStats | null>(null);
    const [failed, setFailed] = useState(false);
    const [mounted, setMounted] = useState(false);

    useEffect(() => {
        let cancelled = false;
        fetch('token-saver-stats.json')
            .then(r => (r.ok ? r.json() : Promise.reject(new Error(String(r.status)))))
            .then((d: TokenSaverStats) => { if (!cancelled) { setStats(d); requestAnimationFrame(() => setMounted(true)); } })
            .catch(() => { if (!cancelled) setFailed(true); });
        return () => { cancelled = true; };
    }, []);

    if (failed) return <div className="tsv tsv-muted">Token Saver stats unavailable.</div>;
    if (!stats) return <div className="tsv tsv-muted">Loading Token Saver…</div>;

    const active = Boolean(stats.skill?.active);
    const saved = stats.savings?.total_estimated_tokens_saved ?? 0;
    const billed = stats.totals?.billed_input_equivalent ?? 0;
    const denom = billed + saved;
    const pct = denom > 0 ? Math.max(0, Math.min(100, (saved / denom) * 100)) : 0;
    const measured = stats.savings?.confidence === 'measured';
    const cache = stats.savings?.cache_reuse_tokens_saved ?? 0;
    const deleg = stats.savings?.delegation_tokens_offloaded ?? 0;
    const mx = Math.max(cache, deleg, 1);

    return (
        <div className="tsv">
            <header className="tsv-head">
                <h3><Zap size={15} /> Token Saver</h3>
                <span className={`tsv-pill ${active ? 'on' : 'off'}`}>
                    {active ? <ShieldCheck size={12} /> : <ShieldOff size={12} />}
                    {active ? 'ACTIVE' : 'INACTIVE'}
                </span>
            </header>

            {!measured ? (
                <p className="tsv-muted">Skill installed — no sessions measured in this scope yet.</p>
            ) : (
                <>
                    <div className="tsv-hero">
                        <div className="tsv-ringbox">
                            <svg width="128" height="128" viewBox="0 0 128 128" className="tsv-ring">
                                <circle cx="64" cy="64" r={R} fill="none" strokeWidth="10" className="tsv-track" />
                                <circle
                                    cx="64" cy="64" r={R} fill="none" strokeWidth="10" strokeLinecap="round"
                                    className="tsv-fill"
                                    strokeDasharray={CIRC}
                                    strokeDashoffset={mounted ? CIRC * (1 - pct / 100) : CIRC}
                                />
                            </svg>
                            <div className="tsv-ctr">
                                <strong>{abbrev(saved)}</strong>
                                <small>{saved.toLocaleString()}</small>
                                <em>tokens saved</em>
                            </div>
                        </div>
                        <div className="tsv-money">
                            <strong>{fmt$(stats.savings?.estimated_usd_saved ?? 0)}</strong>
                            <em>estimated cost avoided</em>
                            <span>{pct.toFixed(1)}% of input · {(stats.totals?.model_calls ?? 0).toLocaleString()} calls</span>
                        </div>
                    </div>

                    <div className="tsv-bars">
                        <div className="tsv-bar">
                            <div className="tsv-barmeta"><span>Cache reuse</span><span>{cache.toLocaleString()}</span></div>
                            <div className="tsv-track2"><div className="tsv-fill2" style={{ width: `${(cache / mx) * 100}%` }} /></div>
                        </div>
                        <div className="tsv-bar">
                            <div className="tsv-barmeta"><span>Delegation offload</span><span>{deleg.toLocaleString()}</span></div>
                            <div className="tsv-track2"><div className="tsv-fill2" style={{ width: `${(deleg / mx) * 100}%` }} /></div>
                        </div>
                    </div>
                </>
            )}

            <p className="tsv-note">{stats.savings?.baseline_note}</p>
        </div>
    );
}
