/**
 * AppFolio-derived fixture — fixed_assets
 *
 * GENERATED by Scripts/derive_appfolio_fixtures.mjs — DO NOT EDIT BY HAND.
 * Source: AppFolio_Screenshots/data/*.json (captured 2026-04-19).
 *
 * Gated by VITE_APPFOLIO_SEEDS per GR-7. When flag is false this module
 * exports empty arrays so no real-person data leaks into public builds.
 */
/* eslint-disable */

const ENABLED = (import.meta as any).env?.VITE_APPFOLIO_SEEDS !== 'false';

export interface AppfolioFixedAsset {
    id: string; propertyId: string;
    name: string | null; installedDate: string | null;
    warrantyExpiration: string | null; cost: number | null;
    notes: string | null; source: string;
}
export const APPFOLIO_FIXED_ASSETS: AppfolioFixedAsset[] = ENABLED ? [
    {
        "id": "appfolio-fa-18-8",
        "propertyId": "appfolio-18",
        "name": "Pump: Pool, Fountain",
        "installedDate": "2021-07-01",
        "warrantyExpiration": "2026-07-01",
        "cost": null,
        "notes": "Installed",
        "source": "appfolio-property-18-fixed-assets"
    },
    {
        "id": "appfolio-fa-18-9",
        "propertyId": "appfolio-18",
        "name": "Pump: Pool, Fountain",
        "installedDate": "2021-07-27",
        "warrantyExpiration": "2026-07-31",
        "cost": null,
        "notes": "Installed",
        "source": "appfolio-property-18-fixed-assets"
    },
    {
        "id": "appfolio-fa-18-15",
        "propertyId": "appfolio-18",
        "name": "Refrigerator",
        "installedDate": "2022-07-19",
        "warrantyExpiration": null,
        "cost": null,
        "notes": "Installed",
        "source": "appfolio-property-18-fixed-assets"
    },
    {
        "id": "appfolio-fa-18-16",
        "propertyId": "appfolio-18",
        "name": "Toilet/Tank/Plumbing",
        "installedDate": "2022-07-16",
        "warrantyExpiration": null,
        "cost": null,
        "notes": "Installed",
        "source": "appfolio-property-18-fixed-assets"
    }
] : [];
