/**
 * AppFolio-derived fixture — leases
 *
 * GENERATED by Scripts/derive_appfolio_fixtures.mjs — DO NOT EDIT BY HAND.
 * Source: AppFolio_Screenshots/data/*.json (captured 2026-04-19).
 *
 * Gated by VITE_APPFOLIO_SEEDS per GR-7. When flag is false this module
 * exports empty arrays so no real-person data leaks into public builds.
 */
/* eslint-disable */

const ENABLED = (import.meta as any).env?.VITE_APPFOLIO_SEEDS !== 'false';

export interface AppfolioLease {
    id: string; tenantName: string | null;
    property: string | null; unit: string | null;
    generatedOn: string | null; status: string; source: string;
}
export const APPFOLIO_LEASES: AppfolioLease[] = ENABLED ? [
    {
        "id": "appfolio-lease-1",
        "tenantName": "Jamel D. Brown*",
        "property": null,
        "unit": "Riverwood Club Apartments - H12",
        "generatedOn": null,
        "status": "ready_to_countersign",
        "source": "appfolio-lease-documents"
    },
    {
        "id": "appfolio-lease-2",
        "tenantName": "Vanessa V. Blunt*",
        "property": null,
        "unit": "Riverwood Club Apartments - D14",
        "generatedOn": null,
        "status": "ready_to_countersign",
        "source": "appfolio-lease-documents"
    }
] : [];
