/**
 * TemplateGenerator — PDF Gear-inspired template engine UI
 * 
 * Features:
 * - HTML-to-PDF generation with live preview
 * - DOCX template variable substitution
 * - Template management (save/load templates)
 * - Variable extraction and form-based editing
 * 
 * Inspired by ncjoes/pdf-gear PHP library features:
 * - setValue() → Variable substitution form
 * - cloneBlock() / deleteBlock() → Block management UI
 * - cloneRow() → Table row duplication
 */
import { useState, useRef, useCallback } from 'react';
import { PDFDocument, rgb, StandardFonts } from 'pdf-lib';
import './TemplateGenerator.css';

// ---- Template Types ----
interface TemplateVariable {
    key: string;
    value: string;
    type: 'text' | 'number' | 'date' | 'currency';
    label?: string;
}

interface TemplateBlock {
    name: string;
    content: string;
    cloned: number; // how many copies
}

type GeneratorTab = 'html' | 'docx' | 'variables';

// ---- Default Templates ----
const DEFAULT_HTML_TEMPLATE = `<!DOCTYPE html>
<html>
<head>
  <style>
    body { font-family: 'Helvetica', sans-serif; padding: 40px; color: #1a1a2e; }
    h1 { color: #2d3436; font-size: 28px; border-bottom: 2px solid #6c5ce7; padding-bottom: 8px; }
    .section { margin: 20px 0; }
    .label { font-weight: bold; color: #636e72; font-size: 12px; text-transform: uppercase; letter-spacing: 1px; }
    .value { font-size: 16px; margin-top: 4px; }
    table { width: 100%; border-collapse: collapse; margin: 20px 0; }
    th { background: #6c5ce7; color: white; padding: 10px; text-align: left; }
    td { padding: 10px; border-bottom: 1px solid #dfe6e9; }
    .footer { margin-top: 40px; font-size: 11px; color: #b2bec3; text-align: center; }
  </style>
</head>
<body>
  <h1>{{title}}</h1>
  <div class="section">
    <div class="label">Prepared For</div>
    <div class="value">{{client_name}}</div>
  </div>
  <div class="section">
    <div class="label">Property</div>
    <div class="value">{{property_address}}</div>
  </div>
  <div class="section">
    <div class="label">Date</div>
    <div class="value">{{date}}</div>
  </div>
  <table>
    <tr><th>Item</th><th>Description</th><th>Amount</th></tr>
    <tr><td>{{item_1}}</td><td>{{desc_1}}</td><td>{{amount_1}}</td></tr>
    <tr><td>{{item_2}}</td><td>{{desc_2}}</td><td>{{amount_2}}</td></tr>
  </table>
  <div class="footer">Generated by Qualia · PDF Gear Engine · {{date}}</div>
</body>
</html>`;

const DEFAULT_VARIABLES: TemplateVariable[] = [
    { key: 'title', value: 'Property Assessment Report', type: 'text', label: 'Document Title' },
    { key: 'client_name', value: 'John Smith', type: 'text', label: 'Client Name' },
    { key: 'property_address', value: '123 Main St, Atlanta GA 30301', type: 'text', label: 'Property Address' },
    { key: 'date', value: new Date().toLocaleDateString(), type: 'date', label: 'Date' },
    { key: 'item_1', value: 'Roof Inspection', type: 'text', label: 'Line Item 1' },
    { key: 'desc_1', value: 'Full roof assessment', type: 'text', label: 'Description 1' },
    { key: 'amount_1', value: '$350.00', type: 'currency', label: 'Amount 1' },
    { key: 'item_2', value: 'HVAC Service', type: 'text', label: 'Line Item 2' },
    { key: 'desc_2', value: 'Annual maintenance', type: 'text', label: 'Description 2' },
    { key: 'amount_2', value: '$200.00', type: 'currency', label: 'Amount 2' },
];

// ---- Component ----
export default function TemplateGenerator() {
    const [activeTab, setActiveTab] = useState<GeneratorTab>('html');
    const [htmlTemplate, setHtmlTemplate] = useState(DEFAULT_HTML_TEMPLATE);
    const [variables, setVariables] = useState<TemplateVariable[]>(DEFAULT_VARIABLES);
    const [blocks, setBlocks] = useState<TemplateBlock[]>([]);
    const [isGenerating, setIsGenerating] = useState(false);
    const [generatedUrl, setGeneratedUrl] = useState<string | null>(null);
    const [previewHtml, setPreviewHtml] = useState<string>('');
    const [toast, setToast] = useState<string | null>(null);
    const iframeRef = useRef<HTMLIFrameElement>(null);

    const showToast = (msg: string) => {
        setToast(msg);
        setTimeout(() => setToast(null), 3000);
    };

    // Substitute variables into template
    const substituteVariables = useCallback((template: string): string => {
        let result = template;
        for (const v of variables) {
            const regex = new RegExp(`\\{\\{${v.key}\\}\\}`, 'g');
            result = result.replace(regex, v.value);
        }
        return result;
    }, [variables]);

    // Extract variables from template
    const extractVariables = useCallback(() => {
        const regex = /\{\{(\w+)\}\}/g;
        const found = new Set<string>();
        let match;
        while ((match = regex.exec(htmlTemplate)) !== null) {
            found.add(match[1]);
        }
        // Merge with existing, keep values for known vars
        const existing = new Map(variables.map(v => [v.key, v]));
        const newVars: TemplateVariable[] = Array.from(found).map(key => {
            if (existing.has(key)) return existing.get(key)!;
            return { key, value: '', type: 'text' as const, label: key.replace(/_/g, ' ') };
        });
        setVariables(newVars);
        showToast(`Extracted ${newVars.length} variables from template`);
    }, [htmlTemplate, variables]);

    // Live preview
    const updatePreview = useCallback(() => {
        const html = substituteVariables(htmlTemplate);
        setPreviewHtml(html);
    }, [htmlTemplate, substituteVariables]);

    // Generate PDF using pdf-lib (client-side)
    const generatePdf = useCallback(async () => {
        setIsGenerating(true);
        try {
            const pdfDoc = await PDFDocument.create();
            const page = pdfDoc.addPage([612, 792]); // US Letter
            const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
            const boldFont = await pdfDoc.embedFont(StandardFonts.HelveticaBold);
            const { height } = page.getSize();

            // Simple text layout from variables
            let y = height - 50;
            const title = variables.find(v => v.key === 'title')?.value || 'Document';

            // Title
            page.drawText(title, {
                x: 50,
                y,
                size: 24,
                font: boldFont,
                color: rgb(0.176, 0.176, 0.294),
            });
            y -= 8;

            // Underline
            page.drawLine({
                start: { x: 50, y },
                end: { x: 562, y },
                thickness: 2,
                color: rgb(0.424, 0.361, 0.906),
            });
            y -= 30;

            // Variables (skip title)
            for (const v of variables) {
                if (v.key === 'title') continue;
                if (y < 80) {
                    // Add new page
                    const newPage = pdfDoc.addPage([612, 792]);
                    y = newPage.getSize().height - 50;
                }

                // Label
                const label = (v.label || v.key.replace(/_/g, ' ')).toUpperCase();
                page.drawText(label, {
                    x: 50,
                    y,
                    size: 9,
                    font: boldFont,
                    color: rgb(0.388, 0.431, 0.447),
                });
                y -= 16;

                // Value
                page.drawText(v.value || '—', {
                    x: 50,
                    y,
                    size: 14,
                    font,
                    color: rgb(0.1, 0.1, 0.1),
                });
                y -= 28;
            }

            // Footer
            page.drawText(`Generated by Qualia · PDF Gear Engine · ${new Date().toLocaleDateString()}`, {
                x: 50,
                y: 30,
                size: 9,
                font,
                color: rgb(0.7, 0.75, 0.78),
            });

            const pdfBytes = await pdfDoc.save();
            const blob = new Blob([pdfBytes.buffer as ArrayBuffer], { type: 'application/pdf' });
            const url = URL.createObjectURL(blob);
            
            if (generatedUrl) URL.revokeObjectURL(generatedUrl);
            setGeneratedUrl(url);
            showToast('PDF generated successfully');
        } catch (err) {
            console.error('PDF generation error:', err);
            showToast('Failed to generate PDF');
        } finally {
            setIsGenerating(false);
        }
    }, [variables, generatedUrl]);

    // Download generated PDF
    const downloadPdf = useCallback(() => {
        if (!generatedUrl) return;
        const a = document.createElement('a');
        a.href = generatedUrl;
        a.download = `${variables.find(v => v.key === 'title')?.value || 'document'}.pdf`;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        showToast('PDF downloaded');
    }, [generatedUrl, variables]);

    // Update a variable
    const updateVariable = (key: string, value: string) => {
        setVariables(prev => prev.map(v => v.key === key ? { ...v, value } : v));
    };

    // Add new variable
    const addVariable = () => {
        const key = `var_${Date.now().toString(36)}`;
        setVariables(prev => [...prev, { key, value: '', type: 'text', label: 'New Variable' }]);
    };

    // Remove variable
    const removeVariable = (key: string) => {
        setVariables(prev => prev.filter(v => v.key !== key));
    };

    // Clone a block (PDF Gear-style)
    const cloneBlock = (blockName: string) => {
        setBlocks(prev => prev.map(b =>
            b.name === blockName ? { ...b, cloned: b.cloned + 1 } : b
        ));
        showToast(`Block "${blockName}" cloned`);
    };

    // Delete a block
    const deleteBlock = (blockName: string) => {
        setBlocks(prev => prev.filter(b => b.name !== blockName));
        showToast(`Block "${blockName}" deleted`);
    };

    return (
        <div className="tg">
            {/* Sidebar Tabs */}
            <div className="tg-sidebar">
                <div className="tg-sidebar__header">
                    <span className="tg-sidebar__icon">⚙️</span>
                    <span className="tg-sidebar__title">PDF Gear</span>
                </div>
                <nav className="tg-sidebar__nav">
                    <button
                        className={`tg-sidebar__tab ${activeTab === 'html' ? 'tg-sidebar__tab--active' : ''}`}
                        onClick={() => setActiveTab('html')}
                    >
                        <span className="tg-sidebar__tab-icon">🌐</span>
                        <span>HTML Template</span>
                    </button>
                    <button
                        className={`tg-sidebar__tab ${activeTab === 'variables' ? 'tg-sidebar__tab--active' : ''}`}
                        onClick={() => setActiveTab('variables')}
                    >
                        <span className="tg-sidebar__tab-icon">📝</span>
                        <span>Variables</span>
                    </button>
                    <button
                        className={`tg-sidebar__tab ${activeTab === 'docx' ? 'tg-sidebar__tab--active' : ''}`}
                        onClick={() => setActiveTab('docx')}
                    >
                        <span className="tg-sidebar__tab-icon">📄</span>
                        <span>DOCX Template</span>
                    </button>
                </nav>

                <div className="tg-sidebar__actions">
                    <button className="tg-action-btn tg-action-btn--primary" onClick={() => void generatePdf()} disabled={isGenerating}>
                        {isGenerating ? '⏳ Generating…' : '🔨 Generate PDF'}
                    </button>
                    {generatedUrl && (
                        <button className="tg-action-btn tg-action-btn--download" onClick={downloadPdf}>
                            ⬇ Download PDF
                        </button>
                    )}
                    <button className="tg-action-btn" onClick={updatePreview}>
                        👁 Preview HTML
                    </button>
                    <button className="tg-action-btn" onClick={extractVariables}>
                        🔍 Extract Variables
                    </button>
                </div>
            </div>

            {/* Main Content */}
            <div className="tg-main">
                {/* HTML Template Editor */}
                {activeTab === 'html' && (
                    <div className="tg-editor">
                        <div className="tg-editor__header">
                            <h3>HTML Template Editor</h3>
                            <span className="tg-editor__hint">
                                Use <code>{'{{variable_name}}'}</code> for dynamic values
                            </span>
                        </div>
                        <textarea
                            className="tg-editor__textarea"
                            value={htmlTemplate}
                            onChange={e => setHtmlTemplate(e.target.value)}
                            spellCheck={false}
                            placeholder="Enter HTML template..."
                        />
                    </div>
                )}

                {/* Variables Form */}
                {activeTab === 'variables' && (
                    <div className="tg-variables">
                        <div className="tg-variables__header">
                            <h3>Template Variables</h3>
                            <button className="tg-add-var-btn" onClick={addVariable}>+ Add Variable</button>
                        </div>
                        <div className="tg-variables__list">
                            {variables.map(v => (
                                <div key={v.key} className="tg-var-row">
                                    <div className="tg-var-row__label">
                                        <span className="tg-var-row__key">{`{{${v.key}}}`}</span>
                                        <span className="tg-var-row__type">{v.type}</span>
                                    </div>
                                    <input
                                        className="tg-var-row__input"
                                        type={v.type === 'number' ? 'number' : 'text'}
                                        value={v.value}
                                        onChange={e => updateVariable(v.key, e.target.value)}
                                        placeholder={v.label || v.key}
                                    />
                                    <button
                                        className="tg-var-row__delete"
                                        onClick={() => removeVariable(v.key)}
                                        title="Remove variable"
                                    >
                                        ✕
                                    </button>
                                </div>
                            ))}
                        </div>

                        {/* Blocks Section (PDF Gear feature) */}
                        {blocks.length > 0 && (
                            <div className="tg-blocks">
                                <h4>Template Blocks</h4>
                                {blocks.map(block => (
                                    <div key={block.name} className="tg-block-row">
                                        <span className="tg-block-row__name">{block.name}</span>
                                        <span className="tg-block-row__count">×{block.cloned + 1}</span>
                                        <button className="tg-block-row__btn" onClick={() => cloneBlock(block.name)}>
                                            Clone
                                        </button>
                                        <button className="tg-block-row__btn tg-block-row__btn--delete" onClick={() => deleteBlock(block.name)}>
                                            Delete
                                        </button>
                                    </div>
                                ))}
                            </div>
                        )}
                    </div>
                )}

                {/* DOCX Template Upload */}
                {activeTab === 'docx' && (
                    <div className="tg-docx">
                        <div className="tg-docx__header">
                            <h3>DOCX Template Engine</h3>
                            <span className="tg-editor__hint">
                                Upload a .docx file with <code>{'{{placeholders}}'}</code> for variable substitution
                            </span>
                        </div>
                        <div className="tg-docx__upload-zone">
                            <span className="tg-docx__upload-icon">📑</span>
                            <p className="tg-docx__upload-text">Drag & drop a .docx template here</p>
                            <p className="tg-docx__upload-hint">
                                Supports setValue, cloneBlock, deleteBlock, and cloneRow operations
                            </p>
                            <label className="tg-action-btn tg-action-btn--primary tg-docx__upload-btn">
                                Browse Files
                                <input type="file" accept=".docx" hidden onChange={() => showToast('DOCX template loaded — variable extraction coming soon')} />
                            </label>
                        </div>
                        <div className="tg-docx__features">
                            <div className="tg-docx__feature">
                                <span className="tg-docx__feature-icon">📝</span>
                                <div>
                                    <strong>setValue()</strong>
                                    <p>Replace placeholder text with dynamic values</p>
                                </div>
                            </div>
                            <div className="tg-docx__feature">
                                <span className="tg-docx__feature-icon">📋</span>
                                <div>
                                    <strong>cloneBlock()</strong>
                                    <p>Duplicate template blocks for repeating sections</p>
                                </div>
                            </div>
                            <div className="tg-docx__feature">
                                <span className="tg-docx__feature-icon">🗑️</span>
                                <div>
                                    <strong>deleteBlock()</strong>
                                    <p>Remove conditional sections from the template</p>
                                </div>
                            </div>
                            <div className="tg-docx__feature">
                                <span className="tg-docx__feature-icon">📊</span>
                                <div>
                                    <strong>cloneRow()</strong>
                                    <p>Duplicate table rows for dynamic data tables</p>
                                </div>
                            </div>
                        </div>
                    </div>
                )}
            </div>

            {/* Preview Panel */}
            <div className="tg-preview">
                <div className="tg-preview__header">
                    <h3>Preview</h3>
                    <span className="tg-preview__badge">
                        {generatedUrl ? 'PDF Ready' : previewHtml ? 'HTML Rendered' : 'No Preview'}
                    </span>
                </div>
                <div className="tg-preview__content">
                    {generatedUrl ? (
                        <iframe
                            className="tg-preview__iframe"
                            src={generatedUrl}
                            title="Generated PDF Preview"
                        />
                    ) : previewHtml ? (
                        <iframe
                            ref={iframeRef}
                            className="tg-preview__iframe"
                            srcDoc={previewHtml}
                            title="HTML Template Preview"
                            sandbox="allow-same-origin"
                        />
                    ) : (
                        <div className="tg-preview__empty">
                            <span className="tg-preview__empty-icon">📄</span>
                            <p>Click "Preview HTML" or "Generate PDF" to see output</p>
                        </div>
                    )}
                </div>
            </div>

            {/* Toast */}
            {toast && <div className="tg-toast">{toast}</div>}
        </div>
    );
}
