import { startTransition, StrictMode } from 'react';
import { hydrateRoot } from 'react-dom/client';
import { HydratedRouter } from 'react-router/dom';

/**
 * Phase-8+ Task 8.7 — React Router v7 framework-mode canonical client entry boundary
 *
 * Custom override of RR v7 default `entry.client.tsx` per Cowork Verdict 12 LOCK
 * (FRAMEWORK-INSTALLATION class 1pt → 2pt CROSS-TASK-SHAPE FULL CALIBRATION at
 * Task 8.7 close; sister-shape constellation to SCOPING-ONLY 2pt FULL CALIBRATION
 * at Tasks 8.1+8.3 + SSR-MIGRATION-PREP 2pt FULL CALIBRATION at Tasks 8.2+8.4).
 *
 * Class definition: NEW sub-shape `entry-boundary-customization-via-entry.client.tsx-+-entry.server.node.tsx`
 * (sister to Task 8.6's `react-router-v7-framework-mode-via-@react-router-dev-vite-plugin` sub-shape).
 *
 * Empirical equivalence to RR v7 default at HEAD-post-Task-8.6 (8e04061) per Q4-d
 * inspection of `node_modules/@react-router/dev/dist/config/defaults/entry.client.tsx`:
 *   - `startTransition` wraps hydration to allow React 19 concurrent renderer to
 *     interrupt the work if higher-priority updates arrive during hydration
 *   - `hydrateRoot(document, ...)` hydrates from the document root (full SSR shell
 *     replacement; matches RR v7 framework-mode HydrateFallback build-time shape)
 *   - `<StrictMode>` enables React 19 strict-mode dev-time effect-double-fire +
 *     deprecated-API warnings (no production runtime cost)
 *   - `<HydratedRouter />` is the canonical RR v7 client-side router primitive
 *     (sister to `<BrowserRouter>` at library-mode altitude but framework-mode-aware)
 *
 * Task 8.8 follow-on: ssr: false → ssr: true flip will make this entry boundary
 * runtime-active for client-side hydration of server-rendered routes. At ssr: false
 * (current state), this entry boundary is invoked at runtime for client-side
 * hydration of the static SPA Mode shell (build/client/index.html) generated by
 * the companion `entry.server.tsx` at build time per Finding W cementation.
 */
startTransition(() => {
    hydrateRoot(
        document,
        <StrictMode>
            <HydratedRouter />
        </StrictMode>,
    );
});
