#!/usr/bin/env node
/**
 * derive_appfolio_fixtures.mjs
 *
 * Phase 0 Task 2 — reads `AppFolio_Screenshots/data/*.json` and emits typed
 * TypeScript fixture constants into
 *   qualia-shell/src/components/StrataDashboard/fixtures/appfolioDerived/
 *
 * One file per entity type. Idempotent: re-running overwrites deterministically.
 *
 * Run: node Scripts/derive_appfolio_fixtures.mjs
 *
 * Fixture files ALL start with a VITE_APPFOLIO_SEEDS guard so an external
 * build (flag=false) treats them as empty arrays and the original anonymized
 * static JSON mocks remain the source of truth (see GR-7).
 */

import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');
const SRC = join(ROOT, 'AppFolio_Screenshots', 'data');
const OUT = join(ROOT, 'qualia-shell', 'src', 'components', 'StrataDashboard', 'fixtures', 'appfolioDerived');

if (!existsSync(OUT)) mkdirSync(OUT, { recursive: true });

const read = (f) => JSON.parse(readFileSync(join(SRC, f), 'utf8'));

// ─── GR-7 sanitizers ───
// Replace real phones/emails/tax-ids with stable placeholders. Idempotent.
const PHONE_RE = /\(\d{3}\)\s*\d{3}-\d{4}|\b\d{3}-\d{3}-\d{4}\b/g;
const EMAIL_RE = /[A-Za-z0-9._%+-]+@(gmail|yahoo|hotmail|outlook|aol|icloud|me|mac|live|msn)\.(com|net|org)\b/gi;
const SSN_MASK_RE = /\bXX-XXX\d{4}\b/g;
const SSN_RAW_RE = /\b\d{3}-\d{2}-\d{4}\b/g;
function sanitizePhone(v) {
    if (v == null) return v;
    if (typeof v !== 'string') return v;
    return v.replace(PHONE_RE, '(555) 555-XXXX');
}
function sanitizeEmail(v, seed = 'x') {
    if (v == null) return v;
    if (typeof v !== 'string') return v;
    // Keep @example.* and @dwellium.test as-is; rewrite anything else that matches real-domain RE.
    return v.replace(EMAIL_RE, () => `tenant-${seed}@example.com`);
}
function sanitizeTaxId(v) {
    if (v == null) return v;
    if (typeof v !== 'string') return v;
    return v.replace(SSN_MASK_RE, 'XX-XX-XXXX').replace(SSN_RAW_RE, 'XX-XX-XXXX');
}
// Deep-walk sanitizer for nested objects (used on vendor.federal_tax, etc.)
function sanitizeAll(obj, seed = 'x') {
    if (obj == null) return obj;
    if (typeof obj === 'string') return sanitizeTaxId(sanitizeEmail(sanitizePhone(obj), seed));
    if (Array.isArray(obj)) return obj.map((x, i) => sanitizeAll(x, `${seed}-${i}`));
    if (typeof obj === 'object') {
        const out = {};
        for (const [k, v] of Object.entries(obj)) out[k] = sanitizeAll(v, seed);
        return out;
    }
    return obj;
}

const HEADER = (entity) => `/**
 * AppFolio-derived fixture — ${entity}
 *
 * GENERATED by Scripts/derive_appfolio_fixtures.mjs — DO NOT EDIT BY HAND.
 * Source: AppFolio_Screenshots/data/*.json (captured 2026-04-19).
 *
 * Gated by VITE_APPFOLIO_SEEDS per GR-7. When flag is false this module
 * exports empty arrays so no real-person data leaks into public builds.
 */
/* eslint-disable */
`;

const FLAG_GATE = `
const ENABLED = (import.meta as any).env?.VITE_APPFOLIO_SEEDS !== 'false';
`;

function write(name, body) {
    const path = join(OUT, name);
    writeFileSync(path, body, 'utf8');
    console.log(`  wrote ${name}  (${body.length} bytes)`);
}

// ─── 1. properties ───
{
    const p1 = read('01_properties_page1.json');
    const p2 = read('02_property_detail_128_buena_vista.json');
    const rows = [
        {
            id: `appfolio-${p2.property_id || 18}`,
            name: p2.name || '128 BUENA VISTA DR N',
            address: p2.address || null,
            city: null,
            state: null,
            zip: null,
            county: p2.county || null,
            yearBuilt: null,
            marketValue: null,
            acquisitionDate: null,
            status: 'active',
            source: 'appfolio-property-detail-18',
        },
        ...((p1.properties_page_1 || p1.properties || []).map((r, i) => ({
            id: `appfolio-p1-${i + 1}`,
            name: r.name || r.property_name || `Property ${i + 1}`,
            address: r.address || null,
            city: r.city || null,
            state: r.state || null,
            zip: r.zip || null,
            county: r.county || null,
            yearBuilt: null,
            marketValue: null,
            acquisitionDate: null,
            status: 'active',
            source: 'appfolio-properties-page1',
        }))),
    ];
    write('properties.ts', HEADER('properties') + FLAG_GATE + `
export interface AppfolioProperty {
    id: string; name: string;
    address: string | null; city: string | null; state: string | null; zip: string | null;
    county: string | null; yearBuilt: number | null; marketValue: number | null;
    acquisitionDate: string | null; status: 'active' | 'inactive'; source: string;
}
export const APPFOLIO_PROPERTIES: AppfolioProperty[] = ENABLED ? ${JSON.stringify(rows, null, 4)} : [];
export const APPFOLIO_PROPERTY_TOTAL = ${p1.total_properties ?? p1.total ?? rows.length};
`);
}

// ─── 2. occupancies (derived from 09) ───
{
    const w = read('09_tenant_detail_willie_white.json');
    const occ = [{
        id: `appfolio-occ-${w.occupancy_id}`,
        propertyName: w.summary?.property_unit ?? null,
        unitLabel: w.summary?.property_unit ?? null,
        leaseEndDate: w.summary?.lease_end_date ?? null,
        monthlyCharges: w.summary?.monthly_charges ?? null,
        currentBalance: w.summary?.current_balance ?? null,
        deposit: w.summary?.deposit ?? null,
        primaryTenantName: w.tenants_on_lease?.primary ?? null,
        otherOccupantNames: w.tenants_on_lease?.other_occupants ?? [],
        onlinePortalStatus: w.summary?.online_portal_status ?? null,
        source: `occupancy-${w.occupancy_id}`,
    }];
    write('occupancies.ts', HEADER('occupancies') + FLAG_GATE + `
export interface AppfolioOccupancy {
    id: string; propertyName: string | null; unitLabel: string | null;
    leaseEndDate: string | null; monthlyCharges: number | null;
    currentBalance: number | null; deposit: number | null;
    primaryTenantName: string | null; otherOccupantNames: string[];
    onlinePortalStatus: string | null; source: string;
}
export const APPFOLIO_OCCUPANCIES: AppfolioOccupancy[] = ENABLED ? ${JSON.stringify(occ, null, 4)} : [];
`);
}

// ─── 3. tenants ───
{
    const t4 = read('04_tenants_page1.json');
    const w = read('09_tenant_detail_willie_white.json');
    const rows = [];
    (t4.sample_tenants_page_1 || t4.rows || []).forEach((r, i) => rows.push({
        id: `appfolio-t-${i + 1}`,
        name: r.name || r.tenant_name || `Tenant ${i + 1}`,
        property: r.property || null,
        unit: r.unit || null,
        status: r.status || 'Past',
        phone: sanitizePhone(r.phone || null),
        email: null, // GR-7 — strip email
        source: 'appfolio-occupancies-page1',
    }));
    if (w?.tenants_on_lease) {
        const occId = w.occupancy_id;
        [w.tenants_on_lease.primary, ...(w.tenants_on_lease.other_occupants || [])]
            .filter(Boolean)
            .forEach((n, i) => rows.push({
                id: `appfolio-t-occ${occId}-${i}`,
                name: n,
                property: 'Riverwood Club Apartments',
                unit: 'B03',
                status: 'Current',
                phone: null,
                email: null,
                source: `occupancy-${occId}`,
                occupantType: i === 0 ? 'Primary' : 'Other Occupant',
                occupancyId: `appfolio-occ-${occId}`,
            }));
    }
    write('tenants.ts', HEADER('tenants') + FLAG_GATE + `
export interface AppfolioTenant {
    id: string; name: string;
    property: string | null; unit: string | null;
    status: 'Current' | 'Past' | 'Future' | string;
    phone: string | null; email: string | null;
    occupantType?: 'Primary' | 'Other Occupant';
    occupancyId?: string;
    source: string;
}
export const APPFOLIO_TENANTS: AppfolioTenant[] = ENABLED ? ${JSON.stringify(rows, null, 4)} : [];
export const APPFOLIO_TENANT_TOTAL = ${t4.total_tenants ?? t4.total ?? rows.length};
`);
}

// ─── 4. vendors ───
{
    const v5 = read('05_vendors_page1.json');
    const v10 = read('10_vendor_detail_2story_roofing.json');
    const rows = [];
    rows.push({
        id: `appfolio-v-${v10.vendor_id}`,
        name: v10.name,
        primaryContactName: v10.primary_contact_name,
        website: v10.website || null,
        vendorType: v10.vendor_type || null,
        phoneType: v10.phone_numbers?.[0]?.type ?? null,
        phone: sanitizePhone(v10.phone_numbers?.[0]?.number ?? null),
        phoneNotes: v10.phone_numbers?.[0]?.notes ?? null,
        emails: (v10.emails || []).map((e, i) => sanitizeEmail(e, `v${v10.vendor_id}-${i}`)),
        primaryAddress: v10.addresses?.[0] ?? null,
        vendorPortalActivated: !!v10.vendor_portal_activated,
        federalTax: sanitizeAll(v10.federal_tax || null, `v${v10.vendor_id}`),
        accounting: sanitizeAll(v10.accounting_information || null, `v${v10.vendor_id}`),
        compliance: v10.compliance || null,
        paymentMethod: v10.accounting_information?.payment_type || null,
        send1099: !!v10.federal_tax?.send_1099,
        notes: sanitizeAll(v10.notes || [], `v${v10.vendor_id}`),
        source: `appfolio-vendor-detail-${v10.vendor_id}`,
    });
    (v5.sample_vendors_page_1 || v5.rows || []).forEach((r, i) => rows.push({
        id: `appfolio-v-p1-${i + 1}`,
        name: r.name || r.vendor_name || `Vendor ${i + 1}`,
        primaryContactName: null,
        website: null,
        vendorType: r.vendor_type || null,
        phoneType: null,
        phone: sanitizePhone(r.phone || null),
        phoneNotes: null,
        emails: [],
        primaryAddress: null,
        vendorPortalActivated: false,
        federalTax: null,
        accounting: null,
        compliance: null,
        paymentMethod: null,
        send1099: false,
        notes: [],
        source: 'appfolio-vendors-page1',
    }));
    write('vendors.ts', HEADER('vendors') + FLAG_GATE + `
export interface AppfolioVendorCompliance {
    workers_comp_expiration: string | null;
    general_liability_expiration: string | null;
    epa_certification_expiration: string | null;
    auto_insurance_expiration: string | null;
    state_license_expiration: string | null;
    contract_expiration: string | null;
    request_compliance_documents_cta?: boolean;
}
export interface AppfolioVendorFederalTax {
    taxpayer_name?: string;
    w9_requested?: boolean;
    tax_id_masked?: string;
    tax_form_account_number?: string;
    send_1099?: boolean;
}
export interface AppfolioVendor {
    id: string; name: string;
    primaryContactName: string | null;
    website: string | null;
    vendorType: string | null;
    phoneType: string | null;
    phone: string | null;
    phoneNotes: string | null;
    emails: string[];
    primaryAddress: { type?: string; street?: string; city?: string; state?: string; zip?: string } | null;
    vendorPortalActivated: boolean;
    federalTax: AppfolioVendorFederalTax | null;
    accounting: Record<string, any> | null;
    compliance: AppfolioVendorCompliance | null;
    paymentMethod: string | null;
    send1099: boolean;
    notes: { posted_by: string; ts: string; body: string }[];
    source: string;
}
export const APPFOLIO_VENDORS: AppfolioVendor[] = ENABLED ? ${JSON.stringify(rows, null, 4)} : [];
export const APPFOLIO_VENDOR_TOTAL = ${v5.total_vendors ?? v5.total ?? rows.length};
`);
}

// ─── 5. workorders ───
{
    const wo3 = read('03_work_orders_page1.json');
    const wo8 = read('08_work_order_detail_19511.json');
    const rows = [];
    // prepend rich detail wo-19511
    const propName = (wo8.property && typeof wo8.property === 'object') ? (wo8.property.name || null) : (wo8.property ?? null);
    const unitLabel = (wo8.property && typeof wo8.property === 'object') ? (wo8.property.unit || null) : (wo8.unit ?? null);
    const residentName = (wo8.resident && typeof wo8.resident === 'object') ? (wo8.resident.name || wo8.resident.tenant_name || null) : (wo8.resident ?? null);
    const ownerName = (wo8.owner && typeof wo8.owner === 'object') ? (wo8.owner.name || null) : (wo8.owner ?? null);
    rows.push({
        id: `appfolio-wo-${wo8.service_request_id ?? 19511}`,
        number: wo8.work_order_number ?? wo8.service_request?.number ?? '19511-1',
        workOrderId: wo8.work_order_id ?? null,
        serviceRequestId: wo8.service_request_id ?? null,
        jobDescription: wo8.service_request?.description ?? wo8.job?.description ?? 'Fire alarm needs replaced',
        priority: wo8.service_request?.priority ?? null,
        status: wo8.status ?? wo8.service_request?.status ?? 'Open',
        property: propName,
        unit: unitLabel,
        resident: residentName,
        residentAvailability: (() => {
            const ra = wo8.scheduling?.resident_availability;
            if (!ra) return [];
            if (Array.isArray(ra)) return ra;
            // Object shape like {monday:"2026-04-20", time_windows_edt:[...]}
            const dayKey = Object.keys(ra).find(k => ['monday','tuesday','wednesday','thursday','friday','saturday','sunday'].includes(k.toLowerCase()));
            const day = dayKey ? ra[dayKey] : null;
            const windows = ra.time_windows_edt || ra.time_windows || [];
            return windows.map((w) => {
                const [start, end] = String(w).split('-').map(s => s.trim());
                return { day, startTime: start || undefined, endTime: end || undefined };
            });
        })(),
        actionsLog: wo8.actions_log ?? [],
        owner: ownerName,
        permissionToEnter: !!(wo8.job?.permission_to_enter ?? wo8.work_order?.permission_to_enter),
        vendorTrade: wo8.job?.vendor_trade ?? wo8.work_order?.vendor_trade ?? null,
        vendorInstructions: wo8.job?.vendor_instructions ?? wo8.work_order?.vendor_instructions ?? null,
        source: 'appfolio-wo-detail-19511',
    });
    (wo3.sample_orders_newest_first || wo3.rows || []).forEach((r, i) => {
        const rProp = (r.property && typeof r.property === 'object') ? (r.property.name || null) : (r.property ?? null);
        const rUnit = (r.property && typeof r.property === 'object') ? (r.property.unit || null) : (r.unit ?? null);
        const rRes = (r.resident && typeof r.resident === 'object') ? (r.resident.name || null) : (r.resident ?? null);
        rows.push({
            id: `appfolio-wo-p1-${i + 1}`,
            number: r.number ?? null,
            workOrderId: null,
            serviceRequestId: null,
            jobDescription: r.description ?? r.title ?? null,
            priority: r.priority ?? null,
            status: r.status ?? 'Open',
            property: rProp,
            unit: rUnit,
            resident: rRes,
            residentAvailability: [],
            actionsLog: [],
            owner: null,
            permissionToEnter: false,
            vendorTrade: null,
            vendorInstructions: null,
            source: 'appfolio-work-orders-page1',
        });
    });
    write('workorders.ts', HEADER('workorders') + FLAG_GATE + `
export interface AppfolioResidentAvailability { day: string; startTime?: string; endTime?: string; notes?: string }
export interface AppfolioActionLogEntry { ts: string; actor: string; event?: string; action?: string; detail?: string }
export interface AppfolioWorkOrder {
    id: string; number: string | null;
    workOrderId: number | null; serviceRequestId: number | null;
    jobDescription: string | null; priority: string | null; status: string;
    property: string | null; unit: string | null; resident: string | null;
    residentAvailability: AppfolioResidentAvailability[];
    actionsLog: AppfolioActionLogEntry[];
    owner: string | null; permissionToEnter: boolean;
    vendorTrade: string | null; vendorInstructions: string | null;
    source: string;
}
export const APPFOLIO_WORK_ORDERS: AppfolioWorkOrder[] = ENABLED ? ${JSON.stringify(rows, null, 4)} : [];
export const APPFOLIO_WORK_ORDER_TOTAL = ${wo3.total_work_orders ?? wo3.total ?? rows.length};
`);
}

// ─── 6. leases ───
{
    const L = read('06_leases.json');
    const src = L.pending_countersign || L.ready_to_countersign || L.rows || [];
    const rows = src.map((r, i) => ({
        id: `appfolio-lease-${i + 1}`,
        tenantName: r.tenant_name ?? r.tenant ?? r.name ?? null,
        property: (r.property && typeof r.property === 'object') ? (r.property.name || null) : (r.property ?? null),
        unit: r.unit ?? null,
        generatedOn: r.generated_on ?? r.generated ?? r.created_on ?? null,
        status: 'ready_to_countersign',
        source: 'appfolio-lease-documents',
    }));
    write('leases.ts', HEADER('leases') + FLAG_GATE + `
export interface AppfolioLease {
    id: string; tenantName: string | null;
    property: string | null; unit: string | null;
    generatedOn: string | null; status: string; source: string;
}
export const APPFOLIO_LEASES: AppfolioLease[] = ENABLED ? ${JSON.stringify(rows, null, 4)} : [];
`);
}

// ─── 7. compliance ───
{
    const c = read('07_insurance_compliance.json');
    const v10 = read('10_vendor_detail_2story_roofing.json');
    // Insurance Enforcement report schema
    const insurance = c.report_columns ?? c.insurance_enforcement_columns ?? c.columns ?? [];
    // 6 vendor compliance rows for 2-Story
    const vExp = v10.compliance || {};
    const vendorRows = [
        ['Workers\' Comp', vExp.workers_comp_expiration],
        ['General Liability', vExp.general_liability_expiration],
        ['EPA Certification', vExp.epa_certification_expiration],
        ['Auto Insurance', vExp.auto_insurance_expiration],
        ['State License', vExp.state_license_expiration],
        ['Contract', vExp.contract_expiration],
    ].map(([kind, exp], i) => ({
        id: `appfolio-comp-v${v10.vendor_id}-${i}`,
        entityType: 'vendor',
        entityId: `appfolio-v-${v10.vendor_id}`,
        entityName: v10.name,
        kind,
        expiration: exp,
        status: exp ? 'tracked' : 'missing',
        source: `vendor-${v10.vendor_id}`,
    }));
    // 9 AHA inspections Riverwood Club 2026-04-27..30
    const ahaRows = Array.from({ length: 9 }, (_, i) => ({
        id: `appfolio-comp-aha-${i + 1}`,
        entityType: 'inspection',
        entityId: 'riverwood-club',
        entityName: 'Riverwood Club Apartments',
        kind: 'Section 8 (AHA) Inspection',
        expiration: ['2026-04-27', '2026-04-28', '2026-04-29', '2026-04-30'][i % 4],
        status: 'scheduled',
        source: 'appfolio-aha-inspection-batch',
    }));
    write('compliance.ts', HEADER('compliance') + FLAG_GATE + `
export interface AppfolioComplianceItem {
    id: string; entityType: 'vendor' | 'inspection' | 'policy' | string;
    entityId: string; entityName: string;
    kind: string; expiration: string | null;
    status: string; source: string;
}
export const APPFOLIO_COMPLIANCE_ITEMS: AppfolioComplianceItem[] = ENABLED ? ${JSON.stringify([...vendorRows, ...ahaRows], null, 4)} : [];
export const APPFOLIO_INSURANCE_ENFORCEMENT_COLUMNS = ${JSON.stringify(insurance, null, 4)};
`);
}

// ─── 8. communications (derived from 09) ───
{
    const w = read('09_tenant_detail_willie_white.json');
    const rows = (w.recent_emails_sample || []).map((e, i) => ({
        id: `appfolio-comm-${i + 1}`,
        channel: 'email',
        direction: 'outbound',
        sentAt: e.sent || null,
        fromAddress: 'ashley.johnson@zp-group.example', // GR-7 sanitized
        toAddress: `tenant-${i}@example.com`, // GR-7 sanitized
        subject: e.subject || null,
        readStatus: e.status || null,
        entityId: `appfolio-occ-${w.occupancy_id}`,
        source: 'appfolio-tenant-emails-willie-white',
    }));
    write('communications.ts', HEADER('communications') + FLAG_GATE + `
export interface AppfolioCommunication {
    id: string;
    channel: 'email' | 'sms' | 'portal' | string;
    direction: 'inbound' | 'outbound';
    sentAt: string | null;
    fromAddress: string | null;
    toAddress: string | null;
    subject: string | null;
    readStatus: string | null;
    entityId: string | null;
    source: string;
}
export const APPFOLIO_COMMUNICATIONS: AppfolioCommunication[] = ENABLED ? ${JSON.stringify(rows, null, 4)} : [];
`);
}

// ─── 9. fixed_assets (derived from 02) ───
{
    const p = read('02_property_detail_128_buena_vista.json');
    const rows = (p.fixed_assets || []).map((a, i) => ({
        id: `appfolio-fa-${p.property_id || 18}-${a.asset_id ?? i}`,
        propertyId: `appfolio-${p.property_id || 18}`,
        name: a.type || a.name || a.asset || null,
        installedDate: a.placed_in_service || a.installed_date || null,
        warrantyExpiration: a.warranty_expiration || null,
        cost: a.cost ?? null,
        notes: a.notes || a.status || null,
        source: `appfolio-property-${p.property_id || 18}-fixed-assets`,
    }));
    write('fixed_assets.ts', HEADER('fixed_assets') + FLAG_GATE + `
export interface AppfolioFixedAsset {
    id: string; propertyId: string;
    name: string | null; installedDate: string | null;
    warrantyExpiration: string | null; cost: number | null;
    notes: string | null; source: string;
}
export const APPFOLIO_FIXED_ASSETS: AppfolioFixedAsset[] = ENABLED ? ${JSON.stringify(rows, null, 4)} : [];
`);
}

// ─── 10. index.ts ───
write('index.ts', HEADER('index barrel') + `
export * from './properties';
export * from './occupancies';
export * from './tenants';
export * from './vendors';
export * from './workorders';
export * from './leases';
export * from './compliance';
export * from './communications';
export * from './fixed_assets';
`);

console.log('\n✓ derive_appfolio_fixtures: emitted 10 files to', OUT);
